import fs from 'fs';
import path from 'path';

const localesDirSrc = path.join(process.cwd(), 'src', 'locales');
const localesDirPub = path.join(process.cwd(), 'public', 'locales');

const translations = {
  ar: {
    "auto_digital_tailor_1032": "خياط رقمي",
    "auto_select_booking_1030": "اختر الحجز",
    "auto_manual_entry_1029": "إدخال يدوي",
    "auto_where_to__1027": "إلى أين؟",
    "auto_vibe_1025": "جو",
    "auto_vibe_1006": "جو",
    "auto_next__body_scan_1024": "التالي: فحص الجسم",
    "auto_ready_to_synthesize__997": "جاهز للتوليف",
    "auto_select_a_booking_or__996": "اختر حجزا أو",
    "auto_heritage_mirror_1031": "مرآة التراث",
    "auto_heritage_mirror_1481": "مرآة التراث",
    "auto_e_g__kyoto__japan_1014": "مثال: كيوتو، اليابان",
    "auto_your_image_1013": "صورتك",
    "auto_click_to_upload_a_ph_1011": "انقر لتحميل صورة",
    "auto_for_best_results__us_1010": "للحصول على أفضل النتائج، استخدم صورة واضحة ومواجهة للأمام.",
    "auto_generate_heritage_im_1009": "توليد صورة التراث",
    "auto_discover_your_herita_993": "اكتشف تراثك",
    "auto_upload_your_photo_an_992": "قم بتحميل صورتك وحدد وجهة لترى نفسك بزي تقليدي.",
    "auto_cyberpunk_2202": "سايبربانك",
    "auto_minimalist_2201": "بسيط",
    "auto_adventurous_2200": "مغامر",
    "auto_sophisticated_2199": "متطور",
    "digitalTailorTitle": "خياط رقمي",
    "heritageMirrorTitle": "مرآة التراث",
    "digitalTailorDesc": "صمم أسلوب سفرك مع روث للذكاء الاصطناعي.",
    "heritageMirrorDesc": "شاهد نفسك بالزي التقليدي."
  },
  de: {
    "auto_digital_tailor_1032": "Digitaler Schneider",
    "auto_select_booking_1030": "Buchung auswählen",
    "auto_manual_entry_1029": "Manuelle Eingabe",
    "auto_where_to__1027": "Wohin?",
    "auto_vibe_1025": "Stimmung",
    "auto_vibe_1006": "Stimmung",
    "auto_next__body_scan_1024": "Weiter: Körperscan",
    "auto_ready_to_synthesize__997": "Bereit zur Synthese",
    "auto_select_a_booking_or__996": "Wählen Sie eine Buchung oder",
    "auto_heritage_mirror_1031": "Erbe-Spiegel",
    "auto_heritage_mirror_1481": "Erbe-Spiegel",
    "auto_e_g__kyoto__japan_1014": "z.B. Kyoto, Japan",
    "auto_your_image_1013": "Ihr Bild",
    "auto_click_to_upload_a_ph_1011": "Klicken Sie zum Hochladen eines Fotos",
    "auto_for_best_results__us_1010": "Für beste Ergebnisse verwenden Sie ein klares Frontalfoto.",
    "auto_generate_heritage_im_1009": "Erbe-Bild generieren",
    "auto_discover_your_herita_993": "Entdecken Sie Ihr Erbe",
    "auto_upload_your_photo_an_992": "Laden Sie Ihr Foto hoch und wählen Sie ein Ziel, um sich in traditioneller Kleidung zu sehen.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalistisch",
    "auto_adventurous_2200": "Abenteuerlich",
    "auto_sophisticated_2199": "Anspruchsvoll",
    "digitalTailorTitle": "Digitaler Schneider",
    "heritageMirrorTitle": "Erbe-Spiegel",
    "digitalTailorDesc": "Synthetisieren Sie Ihren Reisestil mit Ruth AI.",
    "heritageMirrorDesc": "Sehen Sie sich in traditioneller Kleidung."
  },
  en: {
    "auto_digital_tailor_1032": "Digital Tailor",
    "auto_select_booking_1030": "Select Booking",
    "auto_manual_entry_1029": "Manual Entry",
    "auto_where_to__1027": "Where to?",
    "auto_vibe_1025": "Vibe",
    "auto_vibe_1006": "Vibe",
    "auto_next__body_scan_1024": "Next: Body Scan",
    "auto_ready_to_synthesize__997": "Ready to Synthesize",
    "auto_select_a_booking_or__996": "Select a booking or",
    "auto_heritage_mirror_1031": "Heritage Mirror",
    "auto_heritage_mirror_1481": "Heritage Mirror",
    "auto_e_g__kyoto__japan_1014": "e.g., Kyoto, Japan",
    "auto_your_image_1013": "Your Image",
    "auto_click_to_upload_a_ph_1011": "Click to upload a photo",
    "auto_for_best_results__us_1010": "For best results, use a clear, front-facing photo.",
    "auto_generate_heritage_im_1009": "Generate Heritage Image",
    "auto_discover_your_herita_993": "Discover Your Heritage",
    "auto_upload_your_photo_an_992": "Upload your photo and select a destination to see yourself in traditional attire.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalist",
    "auto_adventurous_2200": "Adventurous",
    "auto_sophisticated_2199": "Sophisticated",
    "digitalTailorTitle": "Digital Tailor",
    "heritageMirrorTitle": "Heritage Mirror",
    "digitalTailorDesc": "Synthesize your travel style with Ruth AI.",
    "heritageMirrorDesc": "See yourself in traditional attire."
  },
  es: {
    "auto_digital_tailor_1032": "Sastre Digital",
    "auto_select_booking_1030": "Seleccionar Reserva",
    "auto_manual_entry_1029": "Entrada Manual",
    "auto_where_to__1027": "¿A dónde?",
    "auto_vibe_1025": "Ambiente",
    "auto_vibe_1006": "Ambiente",
    "auto_next__body_scan_1024": "Siguiente: Escaneo Corporal",
    "auto_ready_to_synthesize__997": "Listo para Sintetizar",
    "auto_select_a_booking_or__996": "Selecciona una reserva o",
    "auto_heritage_mirror_1031": "Espejo del Patrimonio",
    "auto_heritage_mirror_1481": "Espejo del Patrimonio",
    "auto_e_g__kyoto__japan_1014": "ej., Kioto, Japón",
    "auto_your_image_1013": "Tu Imagen",
    "auto_click_to_upload_a_ph_1011": "Haz clic para subir una foto",
    "auto_for_best_results__us_1010": "Para mejores resultados, usa una foto clara y de frente.",
    "auto_generate_heritage_im_1009": "Generar Imagen Patrimonial",
    "auto_discover_your_herita_993": "Descubre Tu Patrimonio",
    "auto_upload_your_photo_an_992": "Sube tu foto y selecciona un destino para verte con atuendos tradicionales.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalista",
    "auto_adventurous_2200": "Aventurero",
    "auto_sophisticated_2199": "Sofisticado",
    "digitalTailorTitle": "Sastre Digital",
    "heritageMirrorTitle": "Espejo del Patrimonio",
    "digitalTailorDesc": "Sintetiza tu estilo de viaje con Ruth AI.",
    "heritageMirrorDesc": "Mírate a ti mismo en atuendos tradicionales."
  },
  fr: {
    "auto_digital_tailor_1032": "Tailleur Numérique",
    "auto_select_booking_1030": "Sélectionner la réservation",
    "auto_manual_entry_1029": "Saisie Manuelle",
    "auto_where_to__1027": "Vers où ?",
    "auto_vibe_1025": "Ambiance",
    "auto_vibe_1006": "Ambiance",
    "auto_next__body_scan_1024": "Suivant: Scanner Corporel",
    "auto_ready_to_synthesize__997": "Prêt à Synthétiser",
    "auto_select_a_booking_or__996": "Sélectionnez une réservation ou",
    "auto_heritage_mirror_1031": "Miroir du Patrimoine",
    "auto_heritage_mirror_1481": "Miroir du Patrimoine",
    "auto_e_g__kyoto__japan_1014": "ex., Kyoto, Japon",
    "auto_your_image_1013": "Votre Image",
    "auto_click_to_upload_a_ph_1011": "Cliquez pour télécharger une photo",
    "auto_for_best_results__us_1010": "Pour de meilleurs résultats, utilisez une photo claire de face.",
    "auto_generate_heritage_im_1009": "Générer l'Image du Patrimoine",
    "auto_discover_your_herita_993": "Découvrez Votre Patrimoine",
    "auto_upload_your_photo_an_992": "Téléchargez votre photo et sélectionnez une destination pour vous voir en tenue traditionnelle.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimaliste",
    "auto_adventurous_2200": "Aventureux",
    "auto_sophisticated_2199": "Sophistiqué",
    "digitalTailorTitle": "Tailleur Numérique",
    "heritageMirrorTitle": "Miroir du Patrimoine",
    "digitalTailorDesc": "Synthétisez votre style de voyage avec Ruth AI.",
    "heritageMirrorDesc": "Voyez-vous en tenue traditionnelle."
  },
  hi: {
    "auto_digital_tailor_1032": "डिजिटल दर्जी",
    "auto_select_booking_1030": "बुकिंग चुनें",
    "auto_manual_entry_1029": "मैन्युअल प्रविष्टि",
    "auto_where_to__1027": "कहाँ जाना है?",
    "auto_vibe_1025": "माहौल",
    "auto_vibe_1006": "माहौल",
    "auto_next__body_scan_1024": "अगला: बॉडी स्कैन",
    "auto_ready_to_synthesize__997": "संश्लेषित करने के लिए तैयार",
    "auto_select_a_booking_or__996": "एक बुकिंग चुनें या",
    "auto_heritage_mirror_1031": "विरासत दर्पण",
    "auto_heritage_mirror_1481": "विरासत दर्पण",
    "auto_e_g__kyoto__japan_1014": "उदाहरण: क्योटो, जापान",
    "auto_your_image_1013": "आपकी छवि",
    "auto_click_to_upload_a_ph_1011": "फोटो अपलोड करने के लिए क्लिक करें",
    "auto_for_best_results__us_1010": "सर्वोत्तम परिणामों के लिए, स्पष्ट, सामने वाली तस्वीर का उपयोग करें।",
    "auto_generate_heritage_im_1009": "विरासत छवि उत्पन्न करें",
    "auto_discover_your_herita_993": "अपनी विरासत की खोज करें",
    "auto_upload_your_photo_an_992": "अपनी फोटो अपलोड करें और पारंपरिक पोशाक में खुद को देखने के लिए एक गंतव्य चुनें।",
    "auto_cyberpunk_2202": "साइबरपंक",
    "auto_minimalist_2201": "न्यूनतमवादी",
    "auto_adventurous_2200": "साहसी",
    "auto_sophisticated_2199": "परिष्कृत",
    "digitalTailorTitle": "डिजिटल दर्जी",
    "heritageMirrorTitle": "विरासत दर्पण",
    "digitalTailorDesc": "रूथ एआई के साथ अपनी यात्रा शैली को संश्लेषित करें।",
    "heritageMirrorDesc": "खुद को पारंपरिक पोशाक में देखें।"
  },
  id: {
    "auto_digital_tailor_1032": "Penjahit Digital",
    "auto_select_booking_1030": "Pilih Pemesanan",
    "auto_manual_entry_1029": "Entri Manual",
    "auto_where_to__1027": "Ke mana?",
    "auto_vibe_1025": "Suasana",
    "auto_vibe_1006": "Suasana",
    "auto_next__body_scan_1024": "Selanjutnya: Pemindaian Tubuh",
    "auto_ready_to_synthesize__997": "Siap untuk Mensintesis",
    "auto_select_a_booking_or__996": "Pilih pemesanan atau",
    "auto_heritage_mirror_1031": "Cermin Warisan",
    "auto_heritage_mirror_1481": "Cermin Warisan",
    "auto_e_g__kyoto__japan_1014": "mis., Kyoto, Jepang",
    "auto_your_image_1013": "Gambar Anda",
    "auto_click_to_upload_a_ph_1011": "Klik untuk mengunggah foto",
    "auto_for_best_results__us_1010": "Untuk hasil terbaik, gunakan foto jelas yang menghadap ke depan.",
    "auto_generate_heritage_im_1009": "Hasilkan Gambar Warisan",
    "auto_discover_your_herita_993": "Temukan Warisan Anda",
    "auto_upload_your_photo_an_992": "Unggah foto Anda dan pilih tujuan untuk melihat diri Anda dalam pakaian tradisional.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalis",
    "auto_adventurous_2200": "Petualang",
    "auto_sophisticated_2199": "Canggih",
    "digitalTailorTitle": "Penjahit Digital",
    "heritageMirrorTitle": "Cermin Warisan",
    "digitalTailorDesc": "Sintesis gaya perjalanan Anda dengan Ruth AI.",
    "heritageMirrorDesc": "Lihat diri Anda dalam pakaian tradisional."
  },
  it: {
    "auto_digital_tailor_1032": "Sarto Digitale",
    "auto_select_booking_1030": "Seleziona Prenotazione",
    "auto_manual_entry_1029": "Inserimento Manuale",
    "auto_where_to__1027": "Dove?",
    "auto_vibe_1025": "Atmosfera",
    "auto_vibe_1006": "Atmosfera",
    "auto_next__body_scan_1024": "Avanti: Scansione Corporea",
    "auto_ready_to_synthesize__997": "Pronto a Sintetizzare",
    "auto_select_a_booking_or__996": "Seleziona una prenotazione o",
    "auto_heritage_mirror_1031": "Specchio del Patrimonio",
    "auto_heritage_mirror_1481": "Specchio del Patrimonio",
    "auto_e_g__kyoto__japan_1014": "es., Kyoto, Giappone",
    "auto_your_image_1013": "La tua Immagine",
    "auto_click_to_upload_a_ph_1011": "Fai clic per caricare una foto",
    "auto_for_best_results__us_1010": "Per i migliori risultati, usa una foto chiara frontale.",
    "auto_generate_heritage_im_1009": "Genera Immagine del Patrimonio",
    "auto_discover_your_herita_993": "Scopri il Tuo Patrimonio",
    "auto_upload_your_photo_an_992": "Carica la tua foto e seleziona una destinazione per vederti in abiti tradizionali.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalista",
    "auto_adventurous_2200": "Avventuroso",
    "auto_sophisticated_2199": "Sofisticato",
    "digitalTailorTitle": "Sarto Digitale",
    "heritageMirrorTitle": "Specchio del Patrimonio",
    "digitalTailorDesc": "Sintetizza il tuo stile di viaggio con Ruth AI.",
    "heritageMirrorDesc": "Guardati in abiti tradizionali."
  },
  ja: {
    "auto_digital_tailor_1032": "デジタルテーラー",
    "auto_select_booking_1030": "予約を選択",
    "auto_manual_entry_1029": "手動入力",
    "auto_where_to__1027": "どこへ？",
    "auto_vibe_1025": "雰囲気",
    "auto_vibe_1006": "雰囲気",
    "auto_next__body_scan_1024": "次へ：ボディスキャン",
    "auto_ready_to_synthesize__997": "合成の準備完了",
    "auto_select_a_booking_or__996": "予約を選択するか",
    "auto_heritage_mirror_1031": "ヘリテージミラー",
    "auto_heritage_mirror_1481": "ヘリテージミラー",
    "auto_e_g__kyoto__japan_1014": "例：京都、日本",
    "auto_your_image_1013": "あなたの画像",
    "auto_click_to_upload_a_ph_1011": "クリックして写真をアップロード",
    "auto_for_best_results__us_1010": "最高の結果を得るには、正面の鮮明な写真を使用してください。",
    "auto_generate_heritage_im_1009": "ヘリテージ画像を生成",
    "auto_discover_your_herita_993": "あなたの遺産を発見する",
    "auto_upload_your_photo_an_992": "写真をアップロードし、目的地を選択して伝統的な衣装を着た自分を見てください。",
    "auto_cyberpunk_2202": "サイバーパンク",
    "auto_minimalist_2201": "ミニマリスト",
    "auto_adventurous_2200": "冒険的",
    "auto_sophisticated_2199": "洗練された",
    "digitalTailorTitle": "デジタルテーラー",
    "heritageMirrorTitle": "ヘリテージミラー",
    "digitalTailorDesc": "Ruth AIであなたの旅行スタイルを合成します。",
    "heritageMirrorDesc": "伝統的な衣装を着た自分を見てください。"
  },
  kn: {
    "auto_digital_tailor_1032": "ಡಿಜಿಟಲ್ ಟೈಲರ್",
    "auto_select_booking_1030": "ಬುಕಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ",
    "auto_manual_entry_1029": "ಕೈಯಾರೆ ನಮೂದು",
    "auto_where_to__1027": "ಎಲ್ಲಿಗೆ?",
    "auto_vibe_1025": "ವೈಬ್",
    "auto_vibe_1006": "ವೈಬ್",
    "auto_next__body_scan_1024": "ಮುಂದೆ: ದೇಹ ಸ್ಕ್ಯಾನ್",
    "auto_ready_to_synthesize__997": "ಸಂಶ್ಲೇಷಿಸಲು ಸಿದ್ಧ",
    "auto_select_a_booking_or__996": "ಬುಕಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ",
    "auto_heritage_mirror_1031": "ಹೆರಿಟೇಜ್ ಮಿರರ್",
    "auto_heritage_mirror_1481": "ಹೆರಿಟೇಜ್ ಮಿರರ್",
    "auto_e_g__kyoto__japan_1014": "ಉದಾ., ಕ್ಯೋಟೋ, ಜಪಾನ್",
    "auto_your_image_1013": "ನಿಮ್ಮ ಚಿತ್ರ",
    "auto_click_to_upload_a_ph_1011": "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    "auto_for_best_results__us_1010": "ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ, ಸ್ಪಷ್ಟವಾದ ಮುಂಭಾಗದ ಫೋಟೋವನ್ನು ಬಳಸಿ.",
    "auto_generate_heritage_im_1009": "ಹೆರಿಟೇಜ್ ಚಿತ್ರವನ್ನು ರಚಿಸಿ",
    "auto_discover_your_herita_993": "ನಿಮ್ಮ ಪರಂಪರೆಯನ್ನು ಅನ್ವೇಷಿಸಿ",
    "auto_upload_your_photo_an_992": "ನಿಮ್ಮ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮನ್ನು ಸಾಂಪ್ರದಾಯಿಕ ಉಡುಗೆಯಲ್ಲಿ ನೋಡಲು ಗಮ್ಯಸ್ಥಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    "auto_cyberpunk_2202": "ಸೈಬರ್‌ಪಂಕ್",
    "auto_minimalist_2201": "ಕನಿಷ್ಠ",
    "auto_adventurous_2200": "ಸಾಹಸಮಯ",
    "auto_sophisticated_2199": "ಅತ್ಯಾಧುನಿಕ",
    "digitalTailorTitle": "ಡಿಜಿಟಲ್ ಟೈಲರ್",
    "heritageMirrorTitle": "ಹೆರಿಟೇಜ್ ಮಿರರ್",
    "digitalTailorDesc": "ರೂತ್ ಎಐ ಜೊತೆಗೆ ನಿಮ್ಮ ಪ್ರಯಾಣ ಶೈಲಿಯನ್ನು ಸಂಶ್ಲೇಷಿಸಿ.",
    "heritageMirrorDesc": "ನಿಮ್ಮನ್ನು ಸಾಂಪ್ರದಾಯಿಕ ಉಡುಗೆಯಲ್ಲಿ ನೋಡಿ."
  },
  ml: {
    "auto_digital_tailor_1032": "ഡിജിറ്റൽ ടെയ്‌ലർ",
    "auto_select_booking_1030": "ബുക്കിംഗ് തിരഞ്ഞെടുക്കുക",
    "auto_manual_entry_1029": "മാനുവൽ എൻട്രി",
    "auto_where_to__1027": "എവിടേക്ക്?",
    "auto_vibe_1025": "വൈബ്",
    "auto_vibe_1006": "വൈബ്",
    "auto_next__body_scan_1024": "അടുത്തത്: ബോഡി സ്കാൻ",
    "auto_ready_to_synthesize__997": "സിന്തസൈസ് ചെയ്യാൻ തയ്യാറാണ്",
    "auto_select_a_booking_or__996": "ഒരു ബുക്കിംഗ് തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ",
    "auto_heritage_mirror_1031": "ഹെറിറ്റേജ് മിറർ",
    "auto_heritage_mirror_1481": "ഹെറിറ്റേജ് മിറർ",
    "auto_e_g__kyoto__japan_1014": "ഉദാഹരണത്തിന്, ക്യോട്ടോ, ജപ്പാൻ",
    "auto_your_image_1013": "നിങ്ങളുടെ ചിത്രം",
    "auto_click_to_upload_a_ph_1011": "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്കുചെയ്യുക",
    "auto_for_best_results__us_1010": "മികച്ച ഫലങ്ങൾക്കായി, വ്യക്തമായ മുൻവശത്തെ ഫോട്ടോ ഉപയോഗിക്കുക.",
    "auto_generate_heritage_im_1009": "ഹെറിറ്റേജ് ഇമേജ് സൃഷ്ടിക്കുക",
    "auto_discover_your_herita_993": "നിങ്ങളുടെ പൈതൃകം കണ്ടെത്തുക",
    "auto_upload_your_photo_an_992": "നിങ്ങളുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്‌ത് പരമ്പരാഗത വേഷത്തിൽ നിങ്ങളെ കാണാൻ ഒരു ലക്ഷ്യസ്ഥാനം തിരഞ്ഞെടുക്കുക.",
    "auto_cyberpunk_2202": "സൈബർപങ്ക്",
    "auto_minimalist_2201": "മിനിമലിസ്റ്റ്",
    "auto_adventurous_2200": "സാഹസികമായ",
    "auto_sophisticated_2199": "സങ്കീർണ്ണമായ",
    "digitalTailorTitle": "ഡിജിറ്റൽ ടെയ്‌ലർ",
    "heritageMirrorTitle": "ഹെറിറ്റേജ് മിറർ",
    "digitalTailorDesc": "റൂത്ത് AI ഉപയോഗിച്ച് നിങ്ങളുടെ യാത്രാ ശൈലി സിന്തസൈസ് ചെയ്യുക.",
    "heritageMirrorDesc": "പരമ്പരാഗത വേഷത്തിൽ നിങ്ങളെത്തന്നെ കാണുക."
  },
  ms: {
    "auto_digital_tailor_1032": "Tukang Jahit Digital",
    "auto_select_booking_1030": "Pilih Tempahan",
    "auto_manual_entry_1029": "Kemasukan Manual",
    "auto_where_to__1027": "Ke mana?",
    "auto_vibe_1025": "Suasana",
    "auto_vibe_1006": "Suasana",
    "auto_next__body_scan_1024": "Seterusnya: Imbasan Badan",
    "auto_ready_to_synthesize__997": "Bersedia untuk Mensintesis",
    "auto_select_a_booking_or__996": "Pilih tempahan atau",
    "auto_heritage_mirror_1031": "Cermin Warisan",
    "auto_heritage_mirror_1481": "Cermin Warisan",
    "auto_e_g__kyoto__japan_1014": "cth., Kyoto, Jepun",
    "auto_your_image_1013": "Imej Anda",
    "auto_click_to_upload_a_ph_1011": "Klik untuk memuat naik gambar",
    "auto_for_best_results__us_1010": "Untuk hasil terbaik, gunakan gambar menghadap ke hadapan yang jelas.",
    "auto_generate_heritage_im_1009": "Jana Imej Warisan",
    "auto_discover_your_herita_993": "Temui Warisan Anda",
    "auto_upload_your_photo_an_992": "Muat naik gambar anda dan pilih destinasi untuk melihat diri anda dalam pakaian tradisional.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalis",
    "auto_adventurous_2200": "Pengembara",
    "auto_sophisticated_2199": "Canggih",
    "digitalTailorTitle": "Tukang Jahit Digital",
    "heritageMirrorTitle": "Cermin Warisan",
    "digitalTailorDesc": "Sintesis gaya perjalanan anda dengan Ruth AI.",
    "heritageMirrorDesc": "Lihat diri anda dalam pakaian tradisional."
  },
  nl: {
    "auto_digital_tailor_1032": "Digitale Kleermaker",
    "auto_select_booking_1030": "Boeking Selecteren",
    "auto_manual_entry_1029": "Handmatige Invoer",
    "auto_where_to__1027": "Waarheen?",
    "auto_vibe_1025": "Sfeer",
    "auto_vibe_1006": "Sfeer",
    "auto_next__body_scan_1024": "Volgende: Bodyscan",
    "auto_ready_to_synthesize__997": "Klaar om te Synthetiseren",
    "auto_select_a_booking_or__996": "Selecteer een boeking of",
    "auto_heritage_mirror_1031": "Erfgoedspiegel",
    "auto_heritage_mirror_1481": "Erfgoedspiegel",
    "auto_e_g__kyoto__japan_1014": "bijv., Kyoto, Japan",
    "auto_your_image_1013": "Uw Afbeelding",
    "auto_click_to_upload_a_ph_1011": "Klik om een foto te uploaden",
    "auto_for_best_results__us_1010": "Gebruik voor de beste resultaten een duidelijke foto van voren.",
    "auto_generate_heritage_im_1009": "Erfgoedafbeelding Genereren",
    "auto_discover_your_herita_993": "Ontdek Uw Erfgoed",
    "auto_upload_your_photo_an_992": "Upload uw foto en selecteer een bestemming om uzelf in traditionele kleding te zien.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalistisch",
    "auto_adventurous_2200": "Avontuurlijk",
    "auto_sophisticated_2199": "Verfijnd",
    "digitalTailorTitle": "Digitale Kleermaker",
    "heritageMirrorTitle": "Erfgoedspiegel",
    "digitalTailorDesc": "Synthetiseer uw reisstijl met Ruth AI.",
    "heritageMirrorDesc": "Zie uzelf in traditionele kleding."
  },
  pcm: {
    "auto_digital_tailor_1032": "Digital Tailor",
    "auto_select_booking_1030": "Select Booking",
    "auto_manual_entry_1029": "Manual Entry",
    "auto_where_to__1027": "Where you dey go?",
    "auto_vibe_1025": "Vibe",
    "auto_vibe_1006": "Vibe",
    "auto_next__body_scan_1024": "Next: Body Scan",
    "auto_ready_to_synthesize__997": "Ready to Synthesize",
    "auto_select_a_booking_or__996": "Select a booking or",
    "auto_heritage_mirror_1031": "Heritage Mirror",
    "auto_heritage_mirror_1481": "Heritage Mirror",
    "auto_e_g__kyoto__japan_1014": "e.g., Kyoto, Japan",
    "auto_your_image_1013": "Your Photo",
    "auto_click_to_upload_a_ph_1011": "Click to upload a photo",
    "auto_for_best_results__us_1010": "For best results, use a clear front-facing photo.",
    "auto_generate_heritage_im_1009": "Generate Heritage Image",
    "auto_discover_your_herita_993": "Discover Your Heritage",
    "auto_upload_your_photo_an_992": "Upload your photo and select a destination to see yaself in traditional cloth.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalist",
    "auto_adventurous_2200": "Adventurous",
    "auto_sophisticated_2199": "Sophisticated",
    "digitalTailorTitle": "Digital Tailor",
    "heritageMirrorTitle": "Heritage Mirror",
    "digitalTailorDesc": "Mix ya travel style with Ruth AI.",
    "heritageMirrorDesc": "See yaself in traditional cloth."
  },
  pl: {
    "auto_digital_tailor_1032": "Cyfrowy Krawiec",
    "auto_select_booking_1030": "Wybierz Rezerwację",
    "auto_manual_entry_1029": "Wpis Ręczny",
    "auto_where_to__1027": "Dokąd?",
    "auto_vibe_1025": "Klimat",
    "auto_vibe_1006": "Klimat",
    "auto_next__body_scan_1024": "Dalej: Skan Ciała",
    "auto_ready_to_synthesize__997": "Gotowe do Syntezy",
    "auto_select_a_booking_or__996": "Wybierz rezerwację lub",
    "auto_heritage_mirror_1031": "Lustro Dziedzictwa",
    "auto_heritage_mirror_1481": "Lustro Dziedzictwa",
    "auto_e_g__kyoto__japan_1014": "np. Kioto, Japonia",
    "auto_your_image_1013": "Twoje Zdjęcie",
    "auto_click_to_upload_a_ph_1011": "Kliknij, aby przesłać zdjęcie",
    "auto_for_best_results__us_1010": "Dla najlepszych wyników użyj wyraźnego zdjęcia z przodu.",
    "auto_generate_heritage_im_1009": "Generuj Obraz Dziedzictwa",
    "auto_discover_your_herita_993": "Odkryj Swoje Dziedzictwo",
    "auto_upload_your_photo_an_992": "Prześlij swoje zdjęcie i wybierz cel podróży, aby zobaczyć siebie w tradycyjnym stroju.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalistyczny",
    "auto_adventurous_2200": "Żądny przygód",
    "auto_sophisticated_2199": "Wyrafinowany",
    "digitalTailorTitle": "Cyfrowy Krawiec",
    "heritageMirrorTitle": "Lustro Dziedzictwa",
    "digitalTailorDesc": "Zsyntetyzuj swój styl podróży z Ruth AI.",
    "heritageMirrorDesc": "Zobacz siebie w tradycyjnym stroju."
  },
  pt: {
    "auto_digital_tailor_1032": "Alfaiate Digital",
    "auto_select_booking_1030": "Selecionar Reserva",
    "auto_manual_entry_1029": "Entrada Manual",
    "auto_where_to__1027": "Para onde?",
    "auto_vibe_1025": "Estilo",
    "auto_vibe_1006": "Estilo",
    "auto_next__body_scan_1024": "Avançar: Escaneamento Corporal",
    "auto_ready_to_synthesize__997": "Pronto para Sintetizar",
    "auto_select_a_booking_or__996": "Selecione uma reserva ou",
    "auto_heritage_mirror_1031": "Espelho do Patrimônio",
    "auto_heritage_mirror_1481": "Espelho do Patrimônio",
    "auto_e_g__kyoto__japan_1014": "ex., Quioto, Japão",
    "auto_your_image_1013": "Sua Imagem",
    "auto_click_to_upload_a_ph_1011": "Clique para enviar uma foto",
    "auto_for_best_results__us_1010": "Para obter melhores resultados, use uma foto nítida e frontal.",
    "auto_generate_heritage_im_1009": "Gerar Imagem de Herança",
    "auto_discover_your_herita_993": "Descubra Sua Herança",
    "auto_upload_your_photo_an_992": "Envie sua foto e selecione um destino para ver você em trajes tradicionais.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalista",
    "auto_adventurous_2200": "Aventureiro",
    "auto_sophisticated_2199": "Sofisticado",
    "digitalTailorTitle": "Alfaiate Digital",
    "heritageMirrorTitle": "Espelho do Patrimônio",
    "digitalTailorDesc": "Sintetize seu estilo de viagem com Ruth AI.",
    "heritageMirrorDesc": "Veja a si mesmo com trajes tradicionais."
  },
  ru: {
    "auto_digital_tailor_1032": "Цифровой Портной",
    "auto_select_booking_1030": "Выбрать Бронирование",
    "auto_manual_entry_1029": "Ручной Ввод",
    "auto_where_to__1027": "Куда?",
    "auto_vibe_1025": "Атмосфера",
    "auto_vibe_1006": "Атмосфера",
    "auto_next__body_scan_1024": "Далее: Сканирование тела",
    "auto_ready_to_synthesize__997": "Готово к синтезу",
    "auto_select_a_booking_or__996": "Выберите бронирование или",
    "auto_heritage_mirror_1031": "Зеркало Наследия",
    "auto_heritage_mirror_1481": "Зеркало Наследия",
    "auto_e_g__kyoto__japan_1014": "напр., Киото, Япония",
    "auto_your_image_1013": "Ваше изображение",
    "auto_click_to_upload_a_ph_1011": "Нажмите, чтобы загрузить фото",
    "auto_for_best_results__us_1010": "Для лучшего результата используйте четкое фото анфас.",
    "auto_generate_heritage_im_1009": "Сгенерировать Изображение Наследия",
    "auto_discover_your_herita_993": "Открой свое наследие",
    "auto_upload_your_photo_an_992": "Загрузите свое фото и выберите пункт назначения, чтобы увидеть себя в традиционной одежде.",
    "auto_cyberpunk_2202": "Киберпанк",
    "auto_minimalist_2201": "Минималист",
    "auto_adventurous_2200": "Авантюрный",
    "auto_sophisticated_2199": "Утонченный",
    "digitalTailorTitle": "Цифровой Портной",
    "heritageMirrorTitle": "Зеркало Наследия",
    "digitalTailorDesc": "Синтезируйте свой стиль путешествий с Ruth AI.",
    "heritageMirrorDesc": "Посмотри на себя в традиционной одежде."
  },
  ta: {
    "auto_digital_tailor_1032": "டிஜிட்டல் தையல்காரர்",
    "auto_select_booking_1030": "முன்பதிவைத் தேர்ந்தெடுக்கவும்",
    "auto_manual_entry_1029": "கைமுறையான உள்ளீடு",
    "auto_where_to__1027": "எங்கே செல்வது?",
    "auto_vibe_1025": "அதிர்வு",
    "auto_vibe_1006": "அதிர்வு",
    "auto_next__body_scan_1024": "அடுத்து: உடல் ஸ்கேன்",
    "auto_ready_to_synthesize__997": "ஒருங்கிணைக்க தயார்",
    "auto_select_a_booking_or__996": "முன்பதிவைத் தேர்ந்தெடுக்கவும் அல்லது",
    "auto_heritage_mirror_1031": "பாரம்பரிய கண்ணாடி",
    "auto_heritage_mirror_1481": "பாரம்பரிய கண்ணாடி",
    "auto_e_g__kyoto__japan_1014": "எ.கா. கியோட்டோ, ஜப்பான்",
    "auto_your_image_1013": "உங்கள் படம்",
    "auto_click_to_upload_a_ph_1011": "புகைப்படத்தைப் பதிவேற்ற கிளிக் செய்யவும்",
    "auto_for_best_results__us_1010": "சிறந்த முடிவுகளுக்கு, நேரடியான தெளிவான புகைப்படத்தைப் பயன்படுத்தவும்.",
    "auto_generate_heritage_im_1009": "பாரம்பரிய படத்தை உருவாக்கு",
    "auto_discover_your_herita_993": "உங்கள் பாரம்பரியத்தை கண்டறியவும்",
    "auto_upload_your_photo_an_992": "உங்கள் புகைப்படத்தைப் பதிவேற்றி, பாரம்பரிய உடையில் உங்களைப் பார்க்க இலக்கைத் தேர்ந்தெடுக்கவும்.",
    "auto_cyberpunk_2202": "சைபர்பங்க்",
    "auto_minimalist_2201": "குறைந்தபட்ச",
    "auto_adventurous_2200": "சாகசமான",
    "auto_sophisticated_2199": "நுட்பமான",
    "digitalTailorTitle": "டிஜிட்டல் தையல்காரர்",
    "heritageMirrorTitle": "பாரம்பரிய கண்ணாடி",
    "digitalTailorDesc": "ரூத் AI மூலம் உங்கள் பயண பாணியை ஒருங்கிணைக்கவும்.",
    "heritageMirrorDesc": "பாரம்பரிய உடையில் உங்களைப் பாருங்கள்."
  },
  te: {
    "auto_digital_tailor_1032": "డిజిటల్ టైలర్",
    "auto_select_booking_1030": "బుకింగ్‌ను ఎంచుకోండి",
    "auto_manual_entry_1029": "మాన్యువల్ ఎంట్రీ",
    "auto_where_to__1027": "ఎక్కడికి?",
    "auto_vibe_1025": "వైబ్",
    "auto_vibe_1006": "వైబ్",
    "auto_next__body_scan_1024": "తదుపరి: బాడీ స్కాన్",
    "auto_ready_to_synthesize__997": "సమన్వయం చేయడానికి సిద్ధంగా ఉంది",
    "auto_select_a_booking_or__996": "ఒక బుకింగ్‌ను ఎంచుకోండి లేదా",
    "auto_heritage_mirror_1031": "హెరిటేజ్ మిర్రర్",
    "auto_heritage_mirror_1481": "హెరిటేజ్ మిర్రర్",
    "auto_e_g__kyoto__japan_1014": "ఉదా. క్యోటో, జపాన్",
    "auto_your_image_1013": "మీ చిత్రం",
    "auto_click_to_upload_a_ph_1011": "ఫోటో అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి",
    "auto_for_best_results__us_1010": "ఉత్తమ ఫలితాల కోసం, స్పష్టమైన ముందు వైపు ఫోటోను ఉపయోగించండి.",
    "auto_generate_heritage_im_1009": "హెరిటేజ్ చిత్రాన్ని రూపొందించండి",
    "auto_discover_your_herita_993": "మీ వారసత్వాన్ని కనుగొనండి",
    "auto_upload_your_photo_an_992": "మీ ఫోటోను అప్‌లోడ్ చేయండి మరియు సాంప్రదాయ దుస్తులలో మిమ్మల్ని మీరు చూడటానికి ఒక గమ్యాన్ని ఎంచుకోండి.",
    "auto_cyberpunk_2202": "సైబర్‌పంక్",
    "auto_minimalist_2201": "మినిమలిస్ట్",
    "auto_adventurous_2200": "సాహసోపేతమైన",
    "auto_sophisticated_2199": "అధునాతనమైన",
    "digitalTailorTitle": "డిజిటల్ టైలర్",
    "heritageMirrorTitle": "హెరిటేజ్ మిర్రర్",
    "digitalTailorDesc": "రూత్ AI తో మీ ప్రయాణ శైలిని సమన్వయం చేయండి.",
    "heritageMirrorDesc": "సాంప్రదాయ దుస్తులలో మిమ్మల్ని మీరు చూడండి."
  },
  tl: {
    "auto_digital_tailor_1032": "Digital Tailor",
    "auto_select_booking_1030": "Pumili ng Booking",
    "auto_manual_entry_1029": "Mano-manong Entry",
    "auto_where_to__1027": "Saan papunta?",
    "auto_vibe_1025": "Vibe",
    "auto_vibe_1006": "Vibe",
    "auto_next__body_scan_1024": "Susunod: Body Scan",
    "auto_ready_to_synthesize__997": "Handa na i-synthesize",
    "auto_select_a_booking_or__996": "Pumili ng booking o",
    "auto_heritage_mirror_1031": "Heritage Mirror",
    "auto_heritage_mirror_1481": "Heritage Mirror",
    "auto_e_g__kyoto__japan_1014": "hal., Kyoto, Japan",
    "auto_your_image_1013": "Iyong Larawan",
    "auto_click_to_upload_a_ph_1011": "I-click para mag-upload ng photo",
    "auto_for_best_results__us_1010": "Para sa pinakamahusay na resulta, gumamit ng malinaw at nakaharap na larawan.",
    "auto_generate_heritage_im_1009": "Gumawa ng Heritage Image",
    "auto_discover_your_herita_993": "Tuklasin ang Iyong Pamana",
    "auto_upload_your_photo_an_992": "I-upload ang iyong photo at pumili ng destinasyon upang makita ang iyong sarili sa tradisyonal na kasuotan.",
    "auto_cyberpunk_2202": "Cyberpunk",
    "auto_minimalist_2201": "Minimalist",
    "auto_adventurous_2200": "Adventurous",
    "auto_sophisticated_2199": "Sophisticated",
    "digitalTailorTitle": "Digital Tailor",
    "heritageMirrorTitle": "Heritage Mirror",
    "digitalTailorDesc": "I-synthesize ang iyong travel style sa Ruth AI.",
    "heritageMirrorDesc": "Tingnan ang iyong sarili sa tradisyonal na kasuotan."
  },
  tr: {
    "auto_digital_tailor_1032": "Dijital Terzi",
    "auto_select_booking_1030": "Rezervasyon Seçin",
    "auto_manual_entry_1029": "Manuel Giriş",
    "auto_where_to__1027": "Nereye?",
    "auto_vibe_1025": "Atmosfer",
    "auto_vibe_1006": "Atmosfer",
    "auto_next__body_scan_1024": "Sonraki: Vücut Taraması",
    "auto_ready_to_synthesize__997": "Senteze Hazır",
    "auto_select_a_booking_or__996": "Bir rezervasyon seçin veya",
    "auto_heritage_mirror_1031": "Miras Aynası",
    "auto_heritage_mirror_1481": "Miras Aynası",
    "auto_e_g__kyoto__japan_1014": "Örn: Kyoto, Japonya",
    "auto_your_image_1013": "Görüntünüz",
    "auto_click_to_upload_a_ph_1011": "Fotoğraf yüklemek için tıklayın",
    "auto_for_best_results__us_1010": "En iyi sonuçlar için net, önden çekilmiş bir fotoğraf kullanın.",
    "auto_generate_heritage_im_1009": "Miras Görüntüsü Oluştur",
    "auto_discover_your_herita_993": "Mirasınızı Keşfedin",
    "auto_upload_your_photo_an_992": "Fotoğrafınızı yükleyin ve kendinizi geleneksel kıyafetler içinde görmek için bir hedef seçin.",
    "auto_cyberpunk_2202": "Siberpunk",
    "auto_minimalist_2201": "Minimalist",
    "auto_adventurous_2200": "Maceracı",
    "auto_sophisticated_2199": "Sofistike",
    "digitalTailorTitle": "Dijital Terzi",
    "heritageMirrorTitle": "Miras Aynası",
    "digitalTailorDesc": "Ruth AI ile seyahat tarzınızı sentezleyin.",
    "heritageMirrorDesc": "Kendinizi geleneksel kıyafetler içinde görün."
  },
  ur: {
    "auto_digital_tailor_1032": "ڈیجیٹل ٹیلر",
    "auto_select_booking_1030": "بکنگ منتخب کریں",
    "auto_manual_entry_1029": "دستی اندراج",
    "auto_where_to__1027": "کہاں؟",
    "auto_vibe_1025": "وائب",
    "auto_vibe_1006": "وائب",
    "auto_next__body_scan_1024": "اگلا: باڈی اسکین",
    "auto_ready_to_synthesize__997": "ترکیب کے لیے تیار",
    "auto_select_a_booking_or__996": "کوئی بکنگ منتخب کریں یا",
    "auto_heritage_mirror_1031": "ہیریٹیج آئینہ",
    "auto_heritage_mirror_1481": "ہیریٹیج آئینہ",
    "auto_e_g__kyoto__japan_1014": "مثال کے طور پر، کیوٹو، جاپان",
    "auto_your_image_1013": "آپ کی تصویر",
    "auto_click_to_upload_a_ph_1011": "تصویر اپ لوڈ کرنے کے لیے کلک کریں",
    "auto_for_best_results__us_1010": "بہترین نتائج کے لیے، ایک واضح سامنے والی تصویر استعمال کریں۔",
    "auto_generate_heritage_im_1009": "ہیریٹیج تصویر بنائیں",
    "auto_discover_your_herita_993": "اپنا ورثہ دریافت کریں",
    "auto_upload_your_photo_an_992": "اپنی تصویر اپ لوڈ کریں اور روایتی لباس میں خود کو دیکھنے کے لیے منزل منتخب کریں۔",
    "auto_cyberpunk_2202": "سائبر پنک",
    "auto_minimalist_2201": "منیمالسٹ",
    "auto_adventurous_2200": "مہم جو",
    "auto_sophisticated_2199": "نفیس",
    "digitalTailorTitle": "ڈیجیٹل ٹیلر",
    "heritageMirrorTitle": "ہیریٹیج آئینہ",
    "digitalTailorDesc": "روتھ اے آئی کے ساتھ اپنے سفری انداز کی ترکیب کریں۔",
    "heritageMirrorDesc": "روایتی لباس میں خود کو دیکھیں۔"
  },
  zh: {
    "auto_digital_tailor_1032": "数字裁缝",
    "auto_select_booking_1030": "选择预订",
    "auto_manual_entry_1029": "手动输入",
    "auto_where_to__1027": "去哪里？",
    "auto_vibe_1025": "氛围",
    "auto_vibe_1006": "氛围",
    "auto_next__body_scan_1024": "下一步：身体扫描",
    "auto_ready_to_synthesize__997": "准备生成",
    "auto_select_a_booking_or__996": "选择预订或",
    "auto_heritage_mirror_1031": "遗迹之镜",
    "auto_heritage_mirror_1481": "遗迹之镜",
    "auto_e_g__kyoto__japan_1014": "例如，日本京都",
    "auto_your_image_1013": "您的图像",
    "auto_click_to_upload_a_ph_1011": "点击上传照片",
    "auto_for_best_results__us_1010": "为获得最佳效果，请使用清晰的正面照片。",
    "auto_generate_heritage_im_1009": "生成传统服饰图像",
    "auto_discover_your_herita_993": "探索您的文化遗产",
    "auto_upload_your_photo_an_992": "上传您的照片并选择一个目的地，看看自己穿上传统服饰的样子。",
    "auto_cyberpunk_2202": "赛博朋克",
    "auto_minimalist_2201": "极简主义",
    "auto_adventurous_2200": "冒险",
    "auto_sophisticated_2199": "精致",
    "digitalTailorTitle": "数字裁缝",
    "heritageMirrorTitle": "遗迹之镜",
    "digitalTailorDesc": "与 Ruth AI 一起合成您的旅行风格。",
    "heritageMirrorDesc": "看看自己穿上传统服饰的样子。"
  }
};

async function run() {
  for (const dir of [localesDirSrc, localesDirPub]) {
    if (!fs.existsSync(dir)) continue;
    
    for (const [lang, keys] of Object.entries(translations)) {
      const filePath = path.join(dir, `${lang}.json`);
      if (fs.existsSync(filePath)) {
        const content = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
        
        let changed = false;
        if (!content.auto) {
            content.auto = {};
        }
        for (const [key, val] of Object.entries(keys)) {
          if (content.auto[key] !== val) {
            content.auto[key] = val;
            changed = true;
          }
        }
        
        if (changed) {
          fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n', 'utf-8');
        }
      }
    }
  }
}

run();
