const fs = require('fs');
const path = require('path');

const esData = {
  profile: {
    "title": "Configuración de Perfil",
    "subtitle": "Administra tu identidad y preferencias de Aetheria.",
    "displayName": "Nombre para mostrar",
    "location": "Ubicación",
    "vibe": "Ambiente",
    "bio": "Biografía",
    "selectVibe": "Selecciona tu ambiente",
    "placeholderName": "Tu nombre",
    "placeholderLocation": "ej. Tokio, Japón",
    "placeholderBio": "Cuéntanos sobre tu estilo de viaje...",
    "saveProfile": "Guardar Perfil",
    "profileUpdated": "Perfil actualizado con éxito",
    "travelPreferences": "Preferencias de Viaje",
    "edit": "Editar",
    "savePreferences": "Guardar Preferencias",
    "preferencesSaved": "Preferencias guardadas",
    "currency": "Moneda",
    "language": "Idioma",
    "timezone": "Zona Horaria",
    "units": "Unidades",
    "joined": "Se unió",
    "accountVerified": "Cuenta Verificada"
  },
  journal: {
    "title": "Diario de Viaje",
    "subtitle": "Escribe una crónica de tus aventuras en Aetheria.",
    "newEntry": "Nueva Entrada",
    "newSynthesis": "Nueva Síntesis",
    "entryTitle": "Título de Entrada...",
    "location": "Ubicación...",
    "writeStory": "Escribe tu historia...",
    "cancel": "Cancelar",
    "saveEntry": "Guardar Entrada",
    "noEntries": "Aún no hay entradas. ¡Empieza a escribir tu historia de viaje!",
    "memories": "Recuerdos"
  },
  wallet: {
    "title": "Billetera Inteligente",
    "subtitle": "Administra tus fondos de viaje y el historial de transacciones.",
    "topUp": "Recargar Billetera",
    "aetheriaCard": "Tarjeta Aetheria",
    "activeSynthesis": "Síntesis Activa",
    "availableBalance": "Saldo Disponible",
    "monthlyYield": "Rendimiento Mensual",
    "transactions": "Transacciones",
    "status": "Estado",
    "tier": "Nivel",
    "verified": "Verificado",
    "explorer": "Explorador",
    "spendingSynthesis": "Síntesis de Gastos",
    "last7Days": "Últimos 7 Días",
    "history": "Historial",
    "noTransactions": "Aún no se han sintetizado transacciones.",
    "topUpTitle": "Recargar",
    "amount": "Cantidad",
    "confirmSynthesis": "Confirmar Síntesis",
    "pending": "Pendiente"
  },
  store: {
    "title": "La Tienda Aetheria",
    "subtitle": "Artículos seleccionados para el explorador moderno.",
    "search": "Buscar productos...",
    "anyVibe": "Cualquier Ambiente",
    "anyDestination": "Cualquier Destino",
    "noProducts": "No se encontraron productos que coincidan con tu criterio."
  },
  esim: {
    "title": "Centro Global de eSIM",
    "subtitle": "Sintetiza conectividad instantánea para tus viajes globales.",
    "synthesizeNew": "Sintetizar Nueva eSIM",
    "activeProfiles": "Perfiles Activos",
    "dataUsage": "Uso de Datos",
    "used": "Usado",
    "total": "Total",
    "manageProfile": "Administrar Perfil",
    "noActiveProfiles": "Sin Perfiles Activos",
    "synthesizeDesc": "Sintetiza un nuevo perfil eSIM para mantenerte conectado a través de las fronteras.",
    "instantSynthesis": "Síntesis Instantánea",
    "instantDesc": "Los perfiles se sintetizan y activan en menos de 60 segundos.",
    "secureRoaming": "Roaming Seguro",
    "secureDesc": "Orquestación global de datos con cifrado de extremo a extremo.",
    "realtimeYield": "Rendimiento en Tiempo Real",
    "realtimeDesc": "Monitorea el consumo de datos con precisión de milisegundos.",
    "quickSynthesis": "Síntesis Rápida",
    "searchCountry": "Buscar país...",
    "synthesisTitle": "Síntesis de eSIM",
    "destination": "Destino",
    "chooseCountry": "Elige un país",
    "premiumData": "10GB de Datos Premium",
    "price": "$15.00",
    "details": "Activación instantánea tras la síntesis. Válido por 30 días en todas las redes locales. Incluye orquestación 5G donde esté disponible.",
    "confirmSynthesis": "Confirmar Síntesis"
  },
  navbar: {
    "explore": "Explorar",
    "aiItinerary": "Itinerario con IA",
    "digitalTailor": "Sastre Digital",
    "vibeMarket": "Mercado de Ambientes",
    "globalEsim": "eSIM Global"
  },
  actions: {
    "aiItinerary": "Itinerario con IA",
    "digitalTailor": "Sastre Digital",
    "vibeMarket": "Mercado de Ambientes",
    "vibe": "Ambiente",
    "landmarkLens": "Lente de Puntos de Referencia",
    "wallet": "Billetera",
    "esim": "eSIM",
    "journal": "Diario",
    "budget": "Presupuesto",
    "pathfinder": "Buscador de Rutas",
    "guide": "Guía",
    "arWayfinding": "Navegación AR",
    "localLegends": "Leyendas Locales",
    "profile": "Perfil"
  },
  features: {},
  menu: {
    "sections": {
      "Core Hub": "Centro Principal",
      "AI & Planning": "IA y Planificación",
      "AR & Immersive": "AR e Inmersivo",
      "Food & Gastronomy": "Alimentos y Gastronomía",
      "Wellness & Fitness": "Bienestar y Fitness",
      "Eco & Sustainability": "Eco y Sostenibilidad",
      "Nightlife & Entertainment": "Vida Nocturna y Entretenimiento",
      "Local Culture": "Cultura Local",
      "Safety & Legal": "Seguridad y Legal",
      "Transit & Finance": "Tránsito y Finanzas",
      "Social & Games": "Social y Juegos",
      "Creative & Memories": "Creativo y Recuerdos",
      "Administration": "Administración",
      "Partners": "Socios"
    },
    "items": {
      "Explore": "Explorar",
      "Itineraries": "Itinerarios",
      "AI Itinerary": "Itinerario con IA",
      "Booking Hub": "Centro de Reservas",
      "Digital Tailor": "Sastre Digital",
      "Wallet": "Billetera",
      "eSIM": "eSIM",
      "Store": "Tienda",
      "Journal": "Diario",
      "Profile": "Perfil",
      "Scenario Planner": "Planificador de Escenarios",
      "Serendipity Engine": "Motor de Serendipia",
      "Cognitive Load Balancer": "Equilibrador de Carga Cognitiva",
      "AI Travel Mentor": "Mentor de Viaje con IA",
      "Mood Synthesis": "Síntesis de Estado de Ánimo",
      "Habit Integration": "Integración de Hábitos",
      "Budget Synthesis": "Síntesis de Presupuesto",
      "Weather Adaptive": "Adaptable al Clima",
      "Pathfinder": "Buscador de Rutas",
      "Flavor Seeker": "Buscador de Sabores",
      "AB Testing": "Pruebas AB",
      "Dream Weaver": "Tejedor de Sueños",
      "Challenge Generator": "Generador de Desafíos",
      "AR Wayfinding": "Navegación AR",
      "Landmark Lens": "Lente de Puntos de Referencia",
      "AR Storytelling": "Narración AR",
      "Heritage Mirror": "Espejo de Herencia",
      "AR Menu": "Menú AR",
      "Paint The Town": "Pinta la Ciudad",
      "Sky Gazer": "Observador del Cielo",
      "AR Time Lapse": "Time Lapse AR",
      "AR Art Gallery": "Galería de Arte AR",
      "AR Transit X-Ray": "Rayos X de Tránsito AR",
      "AR Ghost Tours": "Tours de Fantasmas AR",
      "AR Historical": "Histórico AR",
      "AR Ancient Ruins": "Ruinas Antiguas AR",
      "Memory Palace": "Palacio de la Memoria",
      "VR Pre-Trip": "Previo al Viaje en VR",
      "VR Immobile Travel": "Viaje Inmóvil en VR",
      "VR Meditation": "Meditación en VR",
      "VR Extreme Sports": "Deportes Extremos en VR",
      "Postcard Studio": "Estudio de Postales",
      "Video Teaser": "Avance de Video",
      "Audio Guide": "Audioguía",
      "Local Food Bingo": "Bingo de Comida Local",
      "Local Produce Challenge": "Desafío de Productos Locales",
      "Mystery Meal": "Comida Misteriosa",
      "Chef's Table": "Mesa del Chef",
      "Street Food Tour": "Tour de Comida Callejera",
      "Wine Tasting": "Cata de Vinos",
      "Cocktail Companion": "Compañero de Cócteles",
      "Brewery Tour": "Tour de Cervecerías",
      "Coffee Connoisseur": "Conocedor de Café",
      "Tea Ceremony": "Ceremonia del Té",
      "Vegan Finder": "Buscador Vegano",
      "Gluten Free Guide": "Guía Sin Gluten",
      "Food History": "Historia de la Comida",
      "Recipe Collector": "Coleccionista de Recetas",
      "Forage Map": "Mapa de Recolección",
      "Home Cooked Meal": "Comida Casera",
      "Coffee With Local": "Café con un Local",
      "Farm To Table": "De la Granja a la Mesa",
      "Food Blogger Mode": "Modo Bloguero de Comida",
      "Flavor DNA": "ADN del Sabor",
      "Digital Detox": "Desintoxicación Digital",
      "Bio Data Monitor": "Monitor de Datos Biológicos",
      "Personalized Meditation": "Meditación Personalizada",
      "Find A Gym": "Encuentra un Gimnasio",
      "Running Trails": "Rutas de Running",
      "Travel Sleep Tracker": "Rastreador de Sueño de Viaje",
      "Mental Health Support": "Apoyo de Salud Mental",
      "Spa & Wellness": "Spa y Bienestar",
      "Travel Workouts": "Entrenamientos de Viaje",
      "Mindful Walking": "Caminata Consciente",
      "Stress Monitor": "Monitor de Estrés",
      "Hydration Reminder": "Recordatorio de Hidratación",
      "Calorie Tracker": "Rastreador de Calorías",
      "Circadian Protocol": "Protocolo Circadiano",
      "Carbon Synthesis": "Síntesis de Carbono",
      "Eco Warrior Quests": "Misiones de Eco Guerrero",
      "Leave Positive Trace": "Dejar Huella Positiva",
      "Green Transit Score": "Puntaje de Tránsito Verde",
      "Reforestation Rewards": "Recompensas de Reforestación",
      "Sustainable Partners": "Socios Sostenibles",
      "Water Refill Finder": "Buscador de Recarga de Agua",
      "Wildlife Sighting": "Avistamiento de Vida Silvestre",
      "Conservation Circle": "Círculo de Conservación",
      "Animal Translator": "Traductor de Animales",
      "Transport CO2": "CO2 de Transporte",
      "Leave No Trace": "No Dejar Rastro",
      "Volunteer Opportunities": "Oportunidades de Voluntariado",
      "Eco Leaderboard": "Tabla de Clasificación Eco"
    }
  }
};

async function fixES() {
  const dirs = ['src/locales', 'public/locales'];
  for (const dir of dirs) {
    const esPath = path.join(dir, 'es.json');
    if (fs.existsSync(esPath)) {
      const data = JSON.parse(fs.readFileSync(esPath, 'utf8'));
      Object.assign(data, esData);
      fs.writeFileSync(esPath, JSON.stringify(data, null, 2) + '\n', 'utf8');
      console.log('Fixed', esPath);
    }
  }
}

fixES();
