const fs = require('fs');
const path = require('path');

const mlFilePath = path.join(__dirname, 'src', 'locales', 'ml.json');
const data = JSON.parse(fs.readFileSync(mlFilePath, 'utf8'));

if (!data.menu) data.menu = { items: {}, sections: {} };

const itemTranslations = {
  "Carbon Synthesis": "കാർബൺ സിന്തസിസ്",
  "Eco Warrior Quests": "ഇക്കോ വാരിയർ ക്വസ്റ്റുകൾ",
  "Leave Positive Trace": "ലീവ് പോസിറ്റീവ് ട്രേസ്",
  "Green Transit Score": "ഗ്രീൻ ട്രാൻസിറ്റ് സ്കോർ",
  "Reforestation Rewards": "റീഫോറസ്റ്റേഷൻ റിവാർഡുകൾ",
  "Sustainable Partners": "സസ്റ്റൈനബിൾ പാർട്ണേഴ്സ്",
  "Water Refill Finder": "വാട്ടർ റീഫിൽ ഫൈൻഡർ",
  "Wildlife Sighting": "വൈൽഡ് ലൈഫ് സൈറ്റിംഗ്",
  "Conservation Circle": "കൺസർവേഷൻ സർക്കിൾ",
  "Animal Translator": "അനിമൽ ട്രാൻസ്ലേറ്റർ",
  "Transport CO2": "ട്രാൻസ്പോർട്ട് CO2",
  "Leave No Trace": "ലീവ് നോ ട്രേസ്",
  "Volunteer Opportunities": "വോളണ്ടിയർ അവസരങ്ങൾ",
  "Eco Leaderboard": "ഇക്കോ ലീഡർബോർഡ്",
  "Cultural Etiquette": "കൾച്ചറൽ എറ്റിക്കറ്റ്",
  "Myth & Folklore": "മിത്തും നാടോടിക്കഥകളും",
  "Ancestry Trail": "ആൻസെസ്ട്രി ട്രെയിൽ",
  "Local Legends": "ലോക്കൽ ലെജൻഡ്സ്",
  "Local Slang Challenge": "ലോക്കൽ സ്ലാങ് ചലഞ്ച്",
  "Local Dialect Tutor": "ലോക്കൽ ഡയലക്റ്റ് ട്യൂട്ടർ",
  "Skill Exchange Hub": "സ്കിൽ എക്സ്ചേഞ്ച് ഹബ്",
  "Street Art Sagas": "സ്ട്രീറ്റ് ആർട്ട് സാഗാസ്",
  "Translation Earbuds": "ട്രാൻസ്ലേഷൻ ഇയർബഡുകൾ",
  "Translator": "വിവർത്തകൻ",
  "Local Hero Connect": "ലോക്കൽ ഹീറോ കണക്ട്",
  "Live Like A Local": "ലൈവ് ലൈക്ക് എ ലോക്കൽ",
  "Secret Local Spots": "സീക്രട്ട് ലോക്കൽ സ്പോട്ടുകൾ",
  "Artisan Finder": "ആർട്ടിസാൻ ഫൈൻഡർ",
  "Travel Insurance": "ട്രാവൽ ഇൻഷുറൻസ്",
  "Digital Passport": "ഡിജിറ്റൽ പാസ്പോർട്ട്",
  "Scam Alert Radar": "സ്കാം അലർട്ട് റഡാർ",
  "Safety Swarm": "സേഫ്റ്റി സ്വാം",
  "Virtual Embassy": "വിർച്വൽ എംബസി",
  "Emergency Phrases": "എമർജൻസി ഫ്രേസുകൾ",
  "Find A Doctor": "ഡോക്ടറെ കണ്ടെത്തുക",
  "Water Quality Alerts": "വാട്ടർ ക്വാളിറ്റി അലർട്ടുകൾ",
  "Air Quality Alerts": "എയർ ക്വാളിറ്റി അലർട്ടുകൾ",
  "Disaster Warnings": "ഡിസാസ്റ്റർ വാണിംഗ്സ്",
  "Allergen Alert": "അലർജൻ അലർട്ട്",
  "Visa & Passport": "വിസയും പാസ്പോർട്ടും",
  "Vaccination": "വാക്സിനേഷൻ",
  "Get Me Home": "ഗെറ്റ് മി ഹോം",
  "Lost Luggage": "ലോസ്റ്റ് ലഗേജ്",
  "Driving Laws": "ഡ്രൈവിംഗ് നിയമങ്ങൾ",
  "Currency Exchange": "കറൻസി എക്സ്ചേഞ്ച്",
  "Flight Delay Predictor": "ഫ്ലൈറ്റ് ഡിലേ പ്രെഡിക്റ്റർ",
  "Bike & Scooter Rental": "ബൈക്ക് & സ്കൂട്ടർ റെന്റൽ",
  "Ferry Booking": "ഫെറി ബുക്കിംഗ്",
  "Scenic Route Planner": "സീനിക് റൂട്ട് പ്ലാനർ",
  "Layover Adventure": "ലേഓവർ അഡ്വഞ്ചർ",
  "Public Transport Pass": "പബ്ലിക് ട്രാൻസ്പോർട്ട് പാസ്",
  "ATM Finder": "ATM ഫൈൻഡർ",
  "Tax Free Shopping": "ടാക്സ് ഫ്രീ ഷോപ്പിംഗ്",
  "Ticket Aggregator": "ടിക്കറ്റ് അഗ്രിഗേറ്റർ",
  "Traveler Carpooling": "ട്രാവലർ കാർപൂളിംഗ്",
  "Last Mile Transit": "ലാസ്റ്റ് മൈൽ ട്രാൻസിറ്റ്",
  "Rental Synthesizer": "റെന്റൽ സിന്തസൈസർ",
  "Digital Nomad Hub": "ഡിജിറ്റൽ നൊമാഡ് ഹബ്",
  "Travelers Guilds": "ട്രാവലേഴ്സ് ഗിൽഡ്സ്",
  "Faction Wars": "ഫാക്ഷൻ വാർസ്",
  "Bounty Board": "ബൗണ്ടി ബോർഡ്",
  "Travel Charades": "ട്രാവൽ ശാരേഡ്സ്",
  "Global Treasure Hunt": "ഗ്ലോബൽ ട്രെഷർ ഹണ്ട്",
  "City Capture The Flag": "സിറ്റി ക്യാപ്ചർ ദി ഫ്ലാഗ്",
  "Traveler Duels": "ട്രാവലർ ഡ്യുവൽസ്",
  "Shared Expense": "ഷെയേർഡ് എക്സ്പെൻസ്",
  "Pay It Forward": "പേ ഇറ്റ് ഫോർവേഡ്",
  "Collaborative Diary": "കൊളാബറേറ്റീവ് ഡയറി",
  "Itinerary Trading": "ഐറ്റിനററി ട്രേഡിംഗ്",
  "Mystery Pen Pal": "മിസ്റ്ററി പെൻ പാൽ",
  "Guess The Location": "ഗെസ് ദി ലൊക്കേഷൻ",
  "Echoes of Past Travelers": "എക്കോസ് ഓഫ് പാസ്റ്റ് ട്രാവലേഴ്സ്",
  "AI Story Scout": "AI സ്റ്റോറി സ്കൗട്ട്",
  "Meme My Trip": "മീം മൈ ട്രിപ്പ്",
  "AI Blogger": "AI ബ്ലോഗർ",
  "Travel Poem": "ട്രാവൽ പോയം",
  "Memory Mapper": "മെമ്മറി മാപ്പർ",
  "Sensory Journal": "സെൻസറി ജേണൽ",
  "Historical Dialogue Bot": "ഹിസ്റ്റോറിക്കൽ ഡയലോഗ് ബോട്ട്",
  "Postcard AI": "പോസ്റ്റ്കാർഡ് AI",
  "Digital Souvenir Forging": "ഡിജിറ്റൽ സുവനീർ ഫോർജിംഗ്",
  "Travel Tattoo Design": "ട്രാവൽ ടാറ്റൂ ഡിസൈൻ",
  "Trip Color Palette": "ട്രിപ്പ് കളർ പാലറ്റ്",
  "Vibe Filters": "വൈബ് ഫിൽറ്ററുകൾ",
  "Collaborative Scrapbook": "കൊളാബറേറ്റീവ് സ്ക്രാപ്പ്ബുക്ക്",
  "Travel Legacy": "ട്രാവൽ ലെഗസി",
  "Photo Of The Day": "ഫോട്ടോ ഓഫ് ദി ഡേ",
  "Gif Maker": "ജിഫ് മേക്കർ",
  "Vlog Generator": "വ്ലോഗ് ജനറേറ്റർ"
};

for (const [key, value] of Object.entries(itemTranslations)) {
  data.menu.items[key] = value;
}

fs.writeFileSync(mlFilePath, JSON.stringify(data, null, 2));
console.log("ml.json updated with final batch of Malayalam menu items.");
