const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');
const files = fs.readdirSync(localesDir).filter(f => f.endsWith('.json'));

const newKeys = {
  "menu": {
    "sections": {
      "Core Hub": "Core Hub",
      "AI & Planning": "AI & Planning",
      "AR & Immersive": "AR & Immersive",
      "Food & Gastronomy": "Food & Gastronomy",
      "Wellness & Fitness": "Wellness & Fitness",
      "Eco & Sustainability": "Eco & Sustainability",
      "Nightlife & Entertainment": "Nightlife & Entertainment",
      "Local Culture": "Local Culture",
      "Safety & Legal": "Safety & Legal",
      "Transit & Finance": "Transit & Finance",
      "Social & Games": "Social & Games",
      "Creative & Memories": "Creative & Memories",
      "Administration": "Administration",
      "Partners": "Partners"
    },
    "items": {
      "Explore": "Explore",
      "Itineraries": "Itineraries",
      "AI Itinerary": "AI Itinerary",
      "Booking Hub": "Booking Hub",
      "Digital Tailor": "Digital Tailor",
      "Wallet": "Wallet",
      "eSIM": "eSIM",
      "Store": "Store",
      "Journal": "Journal",
      "Profile": "Profile",
      "Scenario Planner": "Scenario Planner",
      "Serendipity Engine": "Serendipity Engine",
      "Cognitive Load Balancer": "Cognitive Load Balancer",
      "AI Travel Mentor": "AI Travel Mentor",
      "Mood Synthesis": "Mood Synthesis",
      "Habit Integration": "Habit Integration",
      "Budget Synthesis": "Budget Synthesis",
      "Weather Adaptive": "Weather Adaptive",
      "Pathfinder": "Pathfinder",
      "Flavor Seeker": "Flavor Seeker",
      "AB Testing": "AB Testing",
      "Dream Weaver": "Dream Weaver",
      "Challenge Generator": "Challenge Generator",
      "AR Wayfinding": "AR Wayfinding",
      "Landmark Lens": "Landmark Lens",
      "AR Storytelling": "AR Storytelling",
      "Heritage Mirror": "Heritage Mirror",
      "AR Menu": "AR Menu",
      "Paint The Town": "Paint The Town",
      "Sky Gazer": "Sky Gazer",
      "AR Time Lapse": "AR Time Lapse",
      "AR Art Gallery": "AR Art Gallery",
      "AR Transit X-Ray": "AR Transit X-Ray",
      "AR Ghost Tours": "AR Ghost Tours",
      "AR Historical": "AR Historical",
      "AR Ancient Ruins": "AR Ancient Ruins",
      "Memory Palace": "Memory Palace",
      "VR Pre-Trip": "VR Pre-Trip",
      "VR Immobile Travel": "VR Immobile Travel",
      "VR Meditation": "VR Meditation",
      "VR Extreme Sports": "VR Extreme Sports",
      "Postcard Studio": "Postcard Studio",
      "Video Teaser": "Video Teaser",
      "Audio Guide": "Audio Guide",
      "Local Food Bingo": "Local Food Bingo",
      "Local Produce Challenge": "Local Produce Challenge",
      "Mystery Meal": "Mystery Meal",
      "Chef's Table": "Chef's Table",
      "Street Food Tour": "Street Food Tour",
      "Wine Tasting": "Wine Tasting",
      "Cocktail Companion": "Cocktail Companion",
      "Brewery Tour": "Brewery Tour",
      "Coffee Connoisseur": "Coffee Connoisseur",
      "Tea Ceremony": "Tea Ceremony",
      "Vegan Finder": "Vegan Finder",
      "Gluten Free Guide": "Gluten Free Guide",
      "Food History": "Food History",
      "Recipe Collector": "Recipe Collector",
      "Forage Map": "Forage Map",
      "Home Cooked Meal": "Home Cooked Meal",
      "Coffee With Local": "Coffee With Local",
      "Farm To Table": "Farm To Table",
      "Food Blogger Mode": "Food Blogger Mode",
      "Flavor DNA": "Flavor DNA",
      "Digital Detox": "Digital Detox",
      "Bio Data Monitor": "Bio Data Monitor",
      "Personalized Meditation": "Personalized Meditation",
      "Find A Gym": "Find A Gym",
      "Running Trails": "Running Trails",
      "Travel Sleep Tracker": "Travel Sleep Tracker",
      "Mental Health Support": "Mental Health Support",
      "Spa & Wellness": "Spa & Wellness",
      "Travel Workouts": "Travel Workouts",
      "Mindful Walking": "Mindful Walking",
      "Stress Monitor": "Stress Monitor",
      "Hydration Reminder": "Hydration Reminder",
      "Calorie Tracker": "Calorie Tracker",
      "Circadian Protocol": "Circadian Protocol",
      "Carbon Synthesis": "Carbon Synthesis",
      "Eco Warrior Quests": "Eco Warrior Quests",
      "Leave Positive Trace": "Leave Positive Trace",
      "Green Transit Score": "Green Transit Score",
      "Reforestation Rewards": "Reforestation Rewards",
      "Sustainable Partners": "Sustainable Partners",
      "Water Refill Finder": "Water Refill Finder",
      "Wildlife Sighting": "Wildlife Sighting",
      "Conservation Circle": "Conservation Circle",
      "Animal Translator": "Animal Translator",
      "Transport CO2": "Transport CO2",
      "Leave No Trace": "Leave No Trace",
      "Volunteer Opportunities": "Volunteer Opportunities",
      "Eco Leaderboard": "Eco Leaderboard",
      "Local Music Scene": "Local Music Scene",
      "Live Music Finder": "Live Music Finder",
      "Festival Forecaster": "Festival Forecaster",
      "Clubbing Guide": "Clubbing Guide",
      "Comedy Club": "Comedy Club",
      "Theater Booking": "Theater Booking",
      "Karaoke Finder": "Karaoke Finder",
      "Speakeasy Guide": "Speakeasy Guide",
      "Night Market": "Night Market",
      "Rooftop Bar": "Rooftop Bar",
      "Stargazing Spots": "Stargazing Spots",
      "Travel Soundtrack": "Travel Soundtrack",
      "Cinema Language": "Cinema Language",
      "Lost In Translation Game": "Lost In Translation Game",
      "Cultural Etiquette": "Cultural Etiquette",
      "Myth & Folklore": "Myth & Folklore",
      "Ancestry Trail": "Ancestry Trail",
      "Local Legends": "Local Legends",
      "Local Slang Challenge": "Local Slang Challenge",
      "Local Dialect Tutor": "Local Dialect Tutor",
      "Skill Exchange Hub": "Skill Exchange Hub",
      "Street Art Sagas": "Street Art Sagas",
      "Translation Earbuds": "Translation Earbuds",
      "Translator": "Translator",
      "Local Hero Connect": "Local Hero Connect",
      "Live Like A Local": "Live Like A Local",
      "Secret Local Spots": "Secret Local Spots",
      "Artisan Finder": "Artisan Finder",
      "Travel Insurance": "Travel Insurance",
      "Digital Passport": "Digital Passport",
      "Scam Alert Radar": "Scam Alert Radar",
      "Safety Swarm": "Safety Swarm",
      "Virtual Embassy": "Virtual Embassy",
      "Emergency Phrases": "Emergency Phrases",
      "Find A Doctor": "Find A Doctor",
      "Water Quality Alerts": "Water Quality Alerts",
      "Air Quality Alerts": "Air Quality Alerts",
      "Disaster Warnings": "Disaster Warnings",
      "Allergen Alert": "Allergen Alert",
      "Visa & Passport": "Visa & Passport",
      "Vaccination": "Vaccination",
      "Get Me Home": "Get Me Home",
      "Lost Luggage": "Lost Luggage",
      "Driving Laws": "Driving Laws",
      "Currency Exchange": "Currency Exchange",
      "Flight Delay Predictor": "Flight Delay Predictor",
      "Bike & Scooter Rental": "Bike & Scooter Rental",
      "Ferry Booking": "Ferry Booking",
      "Scenic Route Planner": "Scenic Route Planner",
      "Layover Adventure": "Layover Adventure",
      "Public Transport Pass": "Public Transport Pass",
      "ATM Finder": "ATM Finder",
      "Tax Free Shopping": "Tax Free Shopping",
      "Ticket Aggregator": "Ticket Aggregator",
      "Traveler Carpooling": "Traveler Carpooling",
      "Last Mile Transit": "Last Mile Transit",
      "Rental Synthesizer": "Rental Synthesizer",
      "Digital Nomad Hub": "Digital Nomad Hub",
      "Travelers Guilds": "Travelers Guilds",
      "Faction Wars": "Faction Wars",
      "Bounty Board": "Bounty Board",
      "Travel Charades": "Travel Charades",
      "Global Treasure Hunt": "Global Treasure Hunt",
      "City Capture The Flag": "City Capture The Flag",
      "Traveler Duels": "Traveler Duels",
      "Shared Expense": "Shared Expense",
      "Pay It Forward": "Pay It Forward",
      "Collaborative Diary": "Collaborative Diary",
      "Itinerary Trading": "Itinerary Trading",
      "Mystery Pen Pal": "Mystery Pen Pal",
      "Guess The Location": "Guess The Location",
      "Echoes of Past Travelers": "Echoes of Past Travelers",
      "AI Story Scout": "AI Story Scout",
      "Meme My Trip": "Meme My Trip",
      "AI Blogger": "AI Blogger",
      "Travel Poem": "Travel Poem",
      "Memory Mapper": "Memory Mapper",
      "Sensory Journal": "Sensory Journal",
      "Historical Dialogue Bot": "Historical Dialogue Bot",
      "Postcard AI": "Postcard AI",
      "Digital Souvenir Forging": "Digital Souvenir Forging",
      "Travel Tattoo Design": "Travel Tattoo Design",
      "Trip Color Palette": "Trip Color Palette",
      "Vibe Filters": "Vibe Filters",
      "Collaborative Scrapbook": "Collaborative Scrapbook",
      "Travel Legacy": "Travel Legacy",
      "Photo Of The Day": "Photo Of The Day",
      "Gif Maker": "Gif Maker",
      "Vlog Generator": "Vlog Generator",
      "Admin Console": "Admin Console",
      "Partner Dashboard": "Partner Dashboard"
    }
  }
};

files.forEach(file => {
  const filePath = path.join(localesDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.menu = newKeys.menu;
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});

console.log("Updated language files.");
