const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');

const translations = {
  ar: {
    welcome: "مرحبًا بعودتك، أيها المستكشف",
    subtitle: "مغامرتك التالية على بعد عملية تركيب واحدة فقط.",
    newItinerary: "مسار رحلة جديد",
    activeItineraries: "مسارات الرحلة النشطة",
    viewAll: "عرض الكل",
    recentActivity: "النشاط الأخير",
    viewHistory: "عرض السجل",
    discoveryHub: "مركز الاكتشاف",
    noItineraries: "لم يتم العثور على مسارات رحلة نشطة. ابدأ بإنشاء واحد!",
    myWallet: "محفظتي",
    manageEsim: "إدارة eSIM",
    startExploring: "ابدأ الاستكشاف",
    aiSynthesize: "التركيب بالذكاء الاصطناعي",
    digitalTailor: "الخياط الرقمي",
    vibeMarket: "سوق الأجواء",
    noActiveItineraries: "لا توجد مسارات رحلة نشطة. ابدأ بإنشاء واحد!"
  },
  de: {
    welcome: "Willkommen zurück, Entdecker",
    subtitle: "Dein nächstes Abenteuer ist nur eine Synthese entfernt.",
    newItinerary: "Neue Reiseroute",
    activeItineraries: "Aktive Reiserouten",
    viewAll: "Alle ansehen",
    recentActivity: "Letzte Aktivitäten",
    viewHistory: "Verlauf ansehen",
    discoveryHub: "Entdeckungszentrum",
    noItineraries: "Keine aktiven Reiserouten gefunden. Beginne mit der Erstellung einer!",
    myWallet: "Meine Brieftasche",
    manageEsim: "eSIM verwalten",
    startExploring: "Erkundung starten",
    aiSynthesize: "KI-Synthese",
    digitalTailor: "Digitaler Schneider",
    vibeMarket: "Vibe-Markt",
    noActiveItineraries: "Keine aktiven Reiserouten gefunden. Beginne mit der Erstellung einer!"
  },
  es: {
    welcome: "Bienvenido de nuevo, Explorador",
    subtitle: "Tu próxima aventura está a solo una síntesis de distancia.",
    newItinerary: "Nuevo Itinerario",
    activeItineraries: "Itinerarios Activos",
    viewAll: "Ver Todo",
    recentActivity: "Actividad Reciente",
    viewHistory: "Ver Historial",
    discoveryHub: "Centro de Descubrimiento",
    noItineraries: "No se encontraron itinerarios activos. ¡Empieza creando uno!",
    myWallet: "Mi Billetera",
    manageEsim: "Gestionar eSIM",
    startExploring: "Empezar a Explorar",
    aiSynthesize: "Sintetizar con IA",
    digitalTailor: "Sastre Digital",
    vibeMarket: "Mercado de Vibras",
    noActiveItineraries: "No hay itinerarios activos. ¡Comienza creando uno!"
  },
  fr: {
    welcome: "Bon retour, Explorateur",
    subtitle: "Votre prochaine aventure n'est qu'à une synthèse.",
    newItinerary: "Nouvel itinéraire",
    activeItineraries: "Itinéraires actifs",
    viewAll: "Voir tout",
    recentActivity: "Activité récente",
    viewHistory: "Voir l'historique",
    discoveryHub: "Centre de découverte",
    noItineraries: "Aucun itinéraire actif trouvé. Commencez par en créer un !",
    myWallet: "Mon portefeuille",
    manageEsim: "Gérer l'eSIM",
    startExploring: "Commencer l'exploration",
    aiSynthesize: "Synthèse IA",
    digitalTailor: "Tailleur Numérique",
    vibeMarket: "Marché des Ambiances",
    noActiveItineraries: "Aucun itinéraire actif trouvé. Commencez par en créer un !"
  },
  hi: {
    welcome: "वापसी पर स्वागत है, एक्सप्लोरर",
    subtitle: "आपका अगला रोमांच बस एक सिंथेसिस दूर है।",
    newItinerary: "नया यात्रा कार्यक्रम",
    activeItineraries: "सक्रिय यात्रा कार्यक्रम",
    viewAll: "सभी देखें",
    recentActivity: "हाल की गतिविधि",
    viewHistory: "इतिहास देखें",
    discoveryHub: "खोज केंद्र",
    noItineraries: "कोई सक्रिय यात्रा कार्यक्रम नहीं मिला। एक बनाना शुरू करें!",
    myWallet: "मेरा बटुआ",
    manageEsim: "eSIM प्रबंधित करें",
    startExploring: "खोजना शुरू करें",
    aiSynthesize: "AI सिंथेसाइज",
    digitalTailor: "डिजिटल दर्जी",
    vibeMarket: "वाइब मार्केट",
    noActiveItineraries: "कोई सक्रिय यात्रा कार्यक्रम नहीं मिला। एक बनाना शुरू करें!"
  },
  id: {
    welcome: "Selamat datang kembali, Penjelajah",
    subtitle: "Petualangan Anda berikutnya hanya berjarak satu sintesis.",
    newItinerary: "Itinerary Baru",
    activeItineraries: "Itinerary Aktif",
    viewAll: "Lihat Semua",
    recentActivity: "Aktivitas Terbaru",
    viewHistory: "Lihat Riwayat",
    discoveryHub: "Pusat Penemuan",
    noItineraries: "Tidak ada itinerary aktif yang ditemukan. Mulailah dengan membuatnya!",
    myWallet: "Dompet Saya",
    manageEsim: "Kelola eSIM",
    startExploring: "Mulai Menjelajah",
    aiSynthesize: "Sintesis AI",
    digitalTailor: "Penjahit Digital",
    vibeMarket: "Pasar Suasana",
    noActiveItineraries: "Tidak ada itinerary aktif yang ditemukan. Mulailah dengan membuat satu!"
  },
  it: {
    welcome: "Bentornato, Esploratore",
    subtitle: "La tua prossima avventura è a una sola sintesi di distanza.",
    newItinerary: "Nuovo itinerario",
    activeItineraries: "Itinerari attivi",
    viewAll: "Mostra tutti",
    recentActivity: "Attività recente",
    viewHistory: "Visualizza cronologia",
    discoveryHub: "Centro Scoperte",
    noItineraries: "Nessun itinerario attivo trovato. Inizia creandone uno!",
    myWallet: "Il mio portafoglio",
    manageEsim: "Gestisci eSIM",
    startExploring: "Inizia a esplorare",
    aiSynthesize: "Sintesi AI",
    digitalTailor: "Sarto Digitale",
    vibeMarket: "Mercato dell'Atmosfera",
    noActiveItineraries: "Nessun itinerario attivo trovato. Inizia creandone uno!"
  },
  ja: {
    welcome: "おかえりなさい、エクスプローラー",
    subtitle: "あなたの次の冒険は、たった一つの合成から始まります。",
    newItinerary: "新しい旅程",
    activeItineraries: "進行中の旅程",
    viewAll: "すべて見る",
    recentActivity: "最近のアクティビティ",
    viewHistory: "履歴を見る",
    discoveryHub: "ディスカバリーハブ",
    noItineraries: "アクティブな旅程が見つかりません。作成してみましょう！",
    myWallet: "マイウォレット",
    manageEsim: "eSIMを管理",
    startExploring: "探索を開始",
    aiSynthesize: "AI合成",
    digitalTailor: "デジタルテーラー",
    vibeMarket: "バイブマーケット",
    noActiveItineraries: "進行中の旅程はありません。作成から始めましょう！"
  },
  kn: {
    welcome: "ಮರಳಿ ಸ್ವಾಗತ, ಎಕ್ಸ್‌ಪ್ಲೋರರ್",
    subtitle: "ನಿಮ್ಮ ಮುಂದಿನ ಸಾಹಸವು ಕೇವಲ ಒಂದು ಸಂಶ್ಲೇಷಣೆಯ ದೂರದಲ್ಲಿದೆ.",
    newItinerary: "ಹೊಸ ಪ್ರವಾಸದ ಯೋಜನೆ",
    activeItineraries: "ಸಕ್ರಿಯ ಪ್ರವಾಸಗಳು",
    viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    viewHistory: "ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಿ",
    discoveryHub: "ಡಿಸ್ಕವರಿ ಹಬ್",
    noItineraries: "ಯಾವುದೇ ಸಕ್ರಿಯ ಪ್ರವಾಸಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಒಂದನ್ನು ರಚಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ!",
    myWallet: "ನನ್ನ ವಾಲೆಟ್",
    manageEsim: "eSIM ನಿರ್ವಹಿಸಿ",
    startExploring: "ಅನ್ವೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
    aiSynthesize: "AI ಸಂಶ್ಲೇಷಣೆ",
    digitalTailor: "ಡಿಜಿಟಲ್ ಟೇಲರ್",
    vibeMarket: "ವೈಬ್ ಮಾರ್ಕೆಟ್",
    noActiveItineraries: "ಯಾವುದೇ ಸಕ್ರಿಯ ಪ್ರವಾಸಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ರಚಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ!"
  },
  ml: {
    welcome: "തിരികെ സ്വാഗതം, പര്യവേക്ഷക",
    subtitle: "നിങ്ങളുടെ അടുത്ത സാഹസികത ഒരു സിന്തസിസ് മാത്രം അകലെയാണ്.",
    newItinerary: "പുതിയ യാത്രാവിവരണം",
    activeItineraries: "സജീവ യാത്രാവിവരണങ്ങൾ",
    viewAll: "എല്ലാം കാണുക",
    recentActivity: "സമീപകാല പ്രവർത്തനം",
    viewHistory: "ചരിത്രം കാണുക",
    discoveryHub: "ഡിസ്കവറി ഹബ്",
    noItineraries: "സജീവ യാത്രാവിവരണങ്ങളൊന്നും കണ്ടെത്തിയില്ല. ഒന്ന് സൃഷ്ടിച്ച് ആരംഭിക്കുക!",
    myWallet: "എന്റെ വാലറ്റ്",
    manageEsim: "eSIM നിയന്ത്രിക്കുക",
    startExploring: "പര്യവേക്ഷണം ആരംഭിക്കുക",
    aiSynthesize: "AI സിന്തസൈസ്",
    digitalTailor: "ഡിജിറ്റൽ ടെയ്ലർ",
    vibeMarket: "വൈബ് മാർക്കറ്റ്",
    noActiveItineraries: "സജീവ യാത്രാവിവരണങ്ങളൊന്നും കണ്ടെത്തിയില്ല. ഒന്ന് സൃഷ്ടിച്ച് ആരംഭിക്കുക!"
  },
  ms: {
    welcome: "Selamat kembali, Penjelajah",
    subtitle: "Pengembaraan seterusnya anda hanya sejauh satu sintesis.",
    newItinerary: "Jadual Perjalanan Baru",
    activeItineraries: "Jadual Aktif",
    viewAll: "Lihat Semua",
    recentActivity: "Aktiviti Terkini",
    viewHistory: "Lihat Sejarah",
    discoveryHub: "Pusat Penemuan",
    noItineraries: "Tiada jadual aktif ditemui. Mulakan dengan mencipta satu!",
    myWallet: "Dompet Saya",
    manageEsim: "Urus eSIM",
    startExploring: "Mula Meneroka",
    aiSynthesize: "Sintesis AI",
    digitalTailor: "Tukang Jahit Digital",
    vibeMarket: "Pasar Suasana",
    noActiveItineraries: "Tiada jadual aktif ditemui. Mulakan dengan mencipta satu!"
  },
  nl: {
    welcome: "Welkom terug, Ontdekkingsreiziger",
    subtitle: "Je volgende avontuur is slechts één synthese verwijderd.",
    newItinerary: "Nieuwe reisroute",
    activeItineraries: "Actieve reisroutes",
    viewAll: "Bekijk alles",
    recentActivity: "Recente activiteit",
    viewHistory: "Bekijk geschiedenis",
    discoveryHub: "Ontdekkingshub",
    noItineraries: "Geen actieve reisroutes gevonden. Begin met er een te maken!",
    myWallet: "Mijn portemonnee",
    manageEsim: "Beheer eSIM",
    startExploring: "Begin met verkennen",
    aiSynthesize: "AI Synthese",
    digitalTailor: "Digitale Kleermaker",
    vibeMarket: "Vibe Markt",
    noActiveItineraries: "Geen actieve reisroutes gevonden. Begin met er een te maken!"
  },
  pcm: {
    welcome: "Welcome back, Explorer",
    subtitle: "Your next adventure just dey one synthesis away.",
    newItinerary: "New Itinerary",
    activeItineraries: "Active Itineraries",
    viewAll: "View All",
    recentActivity: "Recent Activity",
    viewHistory: "View History",
    discoveryHub: "Discovery Hub",
    noItineraries: "No active itineraries found. Start by creating one!",
    myWallet: "My Wallet",
    manageEsim: "Manage eSIM",
    startExploring: "Start Exploring",
    aiSynthesize: "AI Synthesize",
    digitalTailor: "Digital Tailor",
    vibeMarket: "Vibe Market",
    noActiveItineraries: "No active itineraries found. Start by creating one!"
  },
  pl: {
    welcome: "Witamy ponownie, Odkrywco",
    subtitle: "Twoja kolejna przygoda to tylko jedna synteza.",
    newItinerary: "Nowy plan podróży",
    activeItineraries: "Aktywne plany",
    viewAll: "Zobacz wszystko",
    recentActivity: "Ostatnia aktywność",
    viewHistory: "Zobacz historię",
    discoveryHub: "Centrum Odkryć",
    noItineraries: "Nie znaleziono aktywnych planów. Zacznij od utworzenia jednego!",
    myWallet: "Mój portfel",
    manageEsim: "Zarządzaj eSIM",
    startExploring: "Zacznij eksplorować",
    aiSynthesize: "Synteza AI",
    digitalTailor: "Cyfrowy Krawiec",
    vibeMarket: "Rynek Klimatów",
    noActiveItineraries: "Nie znaleziono aktywnych planów podróży. Zacznij od stworzenia jednego!"
  },
  pt: {
    welcome: "Bem-vindo de volta, Explorador",
    subtitle: "A sua próxima aventura está a apenas uma síntese de distância.",
    newItinerary: "Novo Itinerário",
    activeItineraries: "Itinerários Ativos",
    viewAll: "Ver Todos",
    recentActivity: "Atividade Recente",
    viewHistory: "Ver Histórico",
    discoveryHub: "Centro de Descobertas",
    noItineraries: "Nenhum itinerário ativo encontrado. Comece criando um!",
    myWallet: "Minha Carteira",
    manageEsim: "Gerir eSIM",
    startExploring: "Começar a Explorar",
    aiSynthesize: "Sintetizar com IA",
    digitalTailor: "Alfaiate Digital",
    vibeMarket: "Mercado de Vibrações",
    noActiveItineraries: "Nenhum itinerário ativo encontrado. Comece criando um!"
  },
  ru: {
    welcome: "С возвращением, Исследователь",
    subtitle: "До вашего следующего приключения остался всего один синтез.",
    newItinerary: "Новый маршрут",
    activeItineraries: "Активные маршруты",
    viewAll: "Смотреть все",
    recentActivity: "Недавняя активность",
    viewHistory: "Смотреть историю",
    discoveryHub: "Центр открытий",
    noItineraries: "Активных маршрутов не найдено. Начните с создания одного!",
    myWallet: "Мой кошелек",
    manageEsim: "Управление eSIM",
    startExploring: "Начать исследование",
    aiSynthesize: "Синтез ИИ",
    digitalTailor: "Цифровой портной",
    vibeMarket: "Рынок атмосферы",
    noActiveItineraries: "Активных маршрутов не найдено. Начните с создания!"
  },
  ta: {
    welcome: "மீண்டும் வருக, எக்ஸ்ப்ளோரர்",
    subtitle: "உங்கள் அடுத்த சாகசம் ஒரு தொகுப்பு தூரத்தில் உள்ளது.",
    newItinerary: "புதிய பயண திட்டம்",
    activeItineraries: "செயலில் உள்ள பயணங்கள்",
    viewAll: "அனைத்தையும் காண்க",
    recentActivity: "சமீபத்திய செயல்பாடு",
    viewHistory: "வரலாற்றைக் காண்க",
    discoveryHub: "கண்டுபிடிப்பு மையம்",
    noItineraries: "செயலில் உள்ள பயணங்கள் எதுவும் கிடைக்கவில்லை. ஒன்றை உருவாக்குவதன் மூலம் தொடங்கவும்!",
    myWallet: "என் வாலட்",
    manageEsim: "eSIM ஐ நிர்வகிக்கவும்",
    startExploring: "ஆராய்வதைத் தொடங்கவும்",
    aiSynthesize: "AI தொகுப்பு",
    digitalTailor: "டிஜிட்டல் டெய்லர்",
    vibeMarket: "வைப் சந்தை",
    noActiveItineraries: "செயலில் உள்ள பயணங்கள் இல்லை. ஒன்றை உருவாக்குவதன் மூலம் தொடங்கவும்!"
  },
  te: {
    welcome: "తిరిగి స్వాగతం, ఎక్స్‌ప్లోరర్",
    subtitle: "మీ తదుపరి సాహసం ఒక సింథసిస్ దూరంలో ఉంది.",
    newItinerary: "కొత్త ప్రయాణ ప్రణాళిక",
    activeItineraries: "క్రియాశీల ప్రయాణాలు",
    viewAll: "అన్నీ చూడండి",
    recentActivity: "ఇటీవలి కార్యాచరణ",
    viewHistory: "చరిత్రను చూడండి",
    discoveryHub: "డిస్కవరీ హబ్",
    noItineraries: "క్రియాశీల ప్రయాణాలు కనుగొనబడలేదు. ఒకదాన్ని సృష్టించడం ద్వారా ప్రారంభించండి!",
    myWallet: "నా వాలెట్",
    manageEsim: "eSIM నిర్వహించండి",
    startExploring: "అన్వేషించడం ప్రారంభించండి",
    aiSynthesize: "AI సింథసైజ్",
    digitalTailor: "డిజిటల్ టైలర్",
    vibeMarket: "వైబ్ మార్కెట్",
    noActiveItineraries: "క్రియాశీల ప్రయాణాలు ఏవీ కనుగొనబడలేదు. ఒకదాన్ని సృష్టించడం ద్వారా ప్రారంభించండి!"
  },
  tl: {
    welcome: "Maligayang pagbabalik, Explorer",
    subtitle: "Ang iyong susunod na pakikipagsapalaran ay isang synthesis na lang.",
    newItinerary: "Bagong Itinerary",
    activeItineraries: "Mga Aktibong Itinerary",
    viewAll: "Tingnan Lahat",
    recentActivity: "Kamakailang Aktibidad",
    viewHistory: "Tingnan ang Kasaysayan",
    discoveryHub: "Discovery Hub",
    noItineraries: "Walang nahanap na aktibong itinerary. Magsimula sa pamamagitan ng paggawa ng isa!",
    myWallet: "Aking Wallet",
    manageEsim: "Pamahalaan ang eSIM",
    startExploring: "Simulan ang Pag-explore",
    aiSynthesize: "AI Synthesize",
    digitalTailor: "Digital Tailor",
    vibeMarket: "Vibe Market",
    noActiveItineraries: "Walang nahanap na aktibong itinerary. Magsimula sa paggawa ng isa!"
  },
  tr: {
    welcome: "Tekrar hoş geldiniz, Kaşif",
    subtitle: "Bir sonraki maceranız sadece bir sentez uzağınızda.",
    newItinerary: "Yeni Rota",
    activeItineraries: "Aktif Rotalar",
    viewAll: "Tümünü Gör",
    recentActivity: "Son Etkinlik",
    viewHistory: "Geçmişi Gör",
    discoveryHub: "Keşif Merkezi",
    noItineraries: "Aktif rota bulunamadı. Bir tane oluşturarak başlayın!",
    myWallet: "Cüzdanım",
    manageEsim: "eSIM Yönetimi",
    startExploring: "Keşfetmeye Başla",
    aiSynthesize: "Yapay Zeka Sentezi",
    digitalTailor: "Dijital Terzi",
    vibeMarket: "Atmosfer Pazarı",
    noActiveItineraries: "Aktif rota bulunamadı. Bir tane oluşturarak başlayın!"
  },
  ur: {
    welcome: "خوش آمدید، ایکسپلورر",
    subtitle: "آپ کا اگلا ایڈونچر صرف ایک سنتھیسس کی دوری پر ہے۔",
    newItinerary: "نیا سفری نامہ",
    activeItineraries: "فعال سفری نامے",
    viewAll: "سب دیکھیں",
    recentActivity: "حالیہ سرگرمی",
    viewHistory: "تاریخ دیکھیں",
    discoveryHub: "ڈسکوری ہب",
    noItineraries: "کوئی فعال سفری نامہ نہیں ملا۔ ایک بنا کر شروع کریں!",
    myWallet: "میرا والیٹ",
    manageEsim: "eSIM کا نظم کریں",
    startExploring: "تلاش شروع کریں",
    aiSynthesize: "AI سنتھیسس",
    digitalTailor: "ڈیجیٹل ٹیلر",
    vibeMarket: "وائب مارکیٹ",
    noActiveItineraries: "کوئی فعال سفری نامہ نہیں ملا۔ ایک بنا کر شروع کریں!"
  },
  zh: {
    welcome: "欢迎回来，探索者",
    subtitle: "你的下一次冒险距离只有一次合成的距离。",
    newItinerary: "新行程",
    activeItineraries: "活跃行程",
    viewAll: "查看全部",
    recentActivity: "最近活动",
    viewHistory: "查看历史",
    discoveryHub: "探索中心",
    noItineraries: "未找到活跃行程。从创建一个开始吧！",
    myWallet: "我的钱包",
    manageEsim: "管理 eSIM",
    startExploring: "开始探索",
    aiSynthesize: "AI 合成",
    digitalTailor: "数字裁缝",
    vibeMarket: "氛围市场",
    noActiveItineraries: "未找到活跃行程。从创建一个开始吧！"
  }
};

const langs = Object.keys(translations);

for (const lang of langs) {
  const filePath = path.join(localesDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    if (!data.dashboard) {
      data.dashboard = {};
    }
    
    // update strings
    const dashTrans = translations[lang];
    for (const key of Object.keys(dashTrans)) {
      data.dashboard[key] = dashTrans[key];
    }
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated dashboard in ${lang}.json`);
  }
}
