const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');

const enOs = {
  version: "Aetheria OS v2.0",
  readyTo: "Ready to",
  vibeCheck: "vibe check the world?",
  copilotStandby: "Your AI co-pilot is standing by.",
  dropPin: "Drop a pin",
  aiItinerary: "AI Itinerary",
  vibeMarket: "Vibe Market",
  capture: "Capture",
  wallet: "Wallet",
  aiSynthesisEngine: "AI Synthesis Engine",
  tellAetheria: "Tell Aetheria what you want to do...",
  synthesize: "Synthesize",
  tryAsking: "Try asking:",
  tryAsk1: "Plan a 3-day trip to Kyoto",
  tryAsk2: "Find vintage stores in Berlin",
  tryAsk3: "Generate a cyberpunk avatar",
  upcomingDrops: "Upcoming Drops",
  viewAll: "View All",
  noTripsPlanned: "No trips planned yet.",
  systemStatus: "System Status",
  aetheriaCard: "Aetheria Card",
  balanceZero: "$0.00",
  upgradeToPremium: "Upgrade to Premium",
  unlockPremium: "Unlock all AI synthesis engines and premium features.",
  viewPlans: "View Plans",
  bookingHub: "Booking Hub",
  flightsHotelsMore: "Flights, Hotels, & More",
  createTeaser: "Create a Teaser",
  generateTeaserDesc: "AI-generate a cinematic trailer for your next trip to share on socials.",
  generateVideo: "Generate Video",
  spillTheTea: "Spill the tea.",
  logJournalEntry: "Log a new journal entry.",
  brandAetheria: "AETHERIA",
  privacyPolicy: "Privacy Policy",
  termsOfService: "Terms of Service",
  contact: "Contact",
  copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
};

const translations = {
  en: enOs,
  ar: {
    version: "Aetheria OS v2.0",
    readyTo: "مستعد لـ",
    vibeCheck: "التحقق من أجواء العالم؟",
    copilotStandby: "مساعدك الذكي جاهز للمساعدة.",
    dropPin: "إسقاط دبوس",
    aiItinerary: "مسار الرحلة بالذكاء الاصطناعي",
    vibeMarket: "سوق الأجواء",
    capture: "التقاط",
    wallet: "المحفظة",
    aiSynthesisEngine: "محرك التركيب الذكي",
    tellAetheria: "أخبر إيثيريا بما تريد القيام به...",
    synthesize: "تركيب",
    tryAsking: "حاول أن تسأل:",
    tryAsk1: "خطط لرحلة لمدة 3 أيام إلى كيوتو",
    tryAsk2: "ابحث عن المتاجر القديمة في برلين",
    tryAsk3: "قم بإنشاء صورة رمزية بأسلوب سايبربانك",
    upcomingDrops: "الإصدارات القادمة",
    viewAll: "عرض الكل",
    noTripsPlanned: "لا توجد رحلات مخططة بعد.",
    systemStatus: "حالة النظام",
    aetheriaCard: "بطاقة إيثيريا",
    balanceZero: "$0.00",
    upgradeToPremium: "الترقية إلى الإصدار المميز",
    unlockPremium: "افتح جميع محركات التركيب الذكي والميزات المميزة.",
    viewPlans: "عرض الخطط",
    bookingHub: "مركز الحجز",
    flightsHotelsMore: "رحلات طيران وفنادق والمزيد",
    createTeaser: "إنشاء إعلان تشويقي",
    generateTeaserDesc: "قم بإنشاء مقطع دعائي سينمائي لرحلتك القادمة لمشاركته على وسائل التواصل الاجتماعي.",
    generateVideo: "إنشاء فيديو",
    spillTheTea: "شارك القصة.",
    logJournalEntry: "تسجيل إدخال يوميات جديد.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    contact: "اتصل بنا",
    copyright: "© 2026 Aetheria Ecosystem. جميع الحقوق محفوظة."
  },
  de: {
    version: "Aetheria OS v2.0",
    readyTo: "Bereit, um",
    vibeCheck: "den Vibe der Welt zu checken?",
    copilotStandby: "Dein KI-Co-Pilot steht bereit.",
    dropPin: "Stecknadel setzen",
    aiItinerary: "KI-Reiseroute",
    vibeMarket: "Vibe-Markt",
    capture: "Erfassen",
    wallet: "Brieftasche",
    aiSynthesisEngine: "KI-Synthese-Engine",
    tellAetheria: "Sag Aetheria, was du tun möchtest...",
    synthesize: "Synthetisieren",
    tryAsking: "Versuche zu fragen:",
    tryAsk1: "Plane einen 3-tägigen Trip nach Kyoto",
    tryAsk2: "Finde Vintage-Läden in Berlin",
    tryAsk3: "Generiere einen Cyberpunk-Avatar",
    upcomingDrops: "Kommende Drops",
    viewAll: "Alle ansehen",
    noTripsPlanned: "Noch keine Reisen geplant.",
    systemStatus: "Systemstatus",
    aetheriaCard: "Aetheria-Karte",
    balanceZero: "$0.00",
    upgradeToPremium: "Auf Premium upgraden",
    unlockPremium: "Schalte alle KI-Synthese-Engines und Premium-Funktionen frei.",
    viewPlans: "Pläne ansehen",
    bookingHub: "Buchungszentrum",
    flightsHotelsMore: "Flüge, Hotels & Mehr",
    createTeaser: "Teaser erstellen",
    generateTeaserDesc: "Erstelle einen filmischen Trailer für deine nächste Reise, um ihn in den sozialen Medien zu teilen.",
    generateVideo: "Video generieren",
    spillTheTea: "Erzähl die ganze Geschichte.",
    logJournalEntry: "Einen neuen Tagebucheintrag verfassen.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Datenschutzrichtlinie",
    termsOfService: "Nutzungsbedingungen",
    contact: "Kontakt",
    copyright: "© 2026 Aetheria Ecosystem. Alle Rechte vorbehalten."
  },
  es: {
    version: "Aetheria OS v2.0",
    readyTo: "Listo para",
    vibeCheck: "revisar la vibra del mundo?",
    copilotStandby: "Tu copiloto de IA está listo.",
    dropPin: "Fijar un pin",
    aiItinerary: "Itinerario con IA",
    vibeMarket: "Mercado de Vibras",
    capture: "Capturar",
    wallet: "Billetera",
    aiSynthesisEngine: "Motor de Síntesis de IA",
    tellAetheria: "Dile a Aetheria qué quieres hacer...",
    synthesize: "Sintetizar",
    tryAsking: "Intenta preguntar:",
    tryAsk1: "Planea un viaje de 3 días a Kioto",
    tryAsk2: "Encuentra tiendas vintage en Berlín",
    tryAsk3: "Genera un avatar cyberpunk",
    upcomingDrops: "Próximos Lanzamientos",
    viewAll: "Ver Todo",
    noTripsPlanned: "Aún no hay viajes planeados.",
    systemStatus: "Estado del Sistema",
    aetheriaCard: "Tarjeta Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Actualizar a Premium",
    unlockPremium: "Desbloquea todos los motores de síntesis y funciones premium.",
    viewPlans: "Ver Planes",
    bookingHub: "Centro de Reservas",
    flightsHotelsMore: "Vuelos, Hoteles y Más",
    createTeaser: "Crear un Teaser",
    generateTeaserDesc: "Genera con IA un tráiler cinematográfico de tu próximo viaje para redes sociales.",
    generateVideo: "Generar Video",
    spillTheTea: "Cuenta el chisme.",
    logJournalEntry: "Registra una nueva entrada de diario.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    contact: "Contacto",
    copyright: "© 2026 Aetheria Ecosystem. Todos los derechos reservados."
  },
  fr: {
    version: "Aetheria OS v2.0",
    readyTo: "Prêt à",
    vibeCheck: "tester l'ambiance du monde ?",
    copilotStandby: "Votre copilote IA est prêt.",
    dropPin: "Placer un repère",
    aiItinerary: "Itinéraire IA",
    vibeMarket: "Marché des Ambiances",
    capture: "Capturer",
    wallet: "Portefeuille",
    aiSynthesisEngine: "Moteur de Synthèse IA",
    tellAetheria: "Dites à Aetheria ce que vous voulez faire...",
    synthesize: "Synthétiser",
    tryAsking: "Essayez de demander :",
    tryAsk1: "Planifie un voyage de 3 jours à Kyoto",
    tryAsk2: "Trouve des boutiques vintage à Berlin",
    tryAsk3: "Génère un avatar cyberpunk",
    upcomingDrops: "Prochains lancements",
    viewAll: "Voir tout",
    noTripsPlanned: "Aucun voyage prévu pour le moment.",
    systemStatus: "État du système",
    aetheriaCard: "Carte Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Passer à la version Premium",
    unlockPremium: "Débloquez tous les moteurs de synthèse IA et les fonctionnalités premium.",
    viewPlans: "Voir les forfaits",
    bookingHub: "Centre de réservation",
    flightsHotelsMore: "Vols, Hôtels & Plus",
    createTeaser: "Créer un Teaser",
    generateTeaserDesc: "Générez une bande-annonce cinématographique IA pour votre prochain voyage.",
    generateVideo: "Générer la vidéo",
    spillTheTea: "Raconte les potins.",
    logJournalEntry: "Enregistrez une nouvelle entrée de journal.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions de service",
    contact: "Contact",
    copyright: "© 2026 Aetheria Ecosystem. Tous droits réservés."
  },
  hi: {
    version: "Aetheria OS v2.0",
    readyTo: "क्या आप तैयार हैं",
    vibeCheck: "दुनिया का वाइब चेक करने के लिए?",
    copilotStandby: "आपका AI सह-पायलट तैयार है।",
    dropPin: "एक पिन छोड़ें",
    aiItinerary: "AI यात्रा कार्यक्रम",
    vibeMarket: "वाइब मार्केट",
    capture: "कैप्चर करें",
    wallet: "बटुआ",
    aiSynthesisEngine: "AI सिंथेसिस इंजन",
    tellAetheria: "Aetheria को बताएं कि आप क्या करना चाहते हैं...",
    synthesize: "सिंथेसाइज",
    tryAsking: "यह पूछने का प्रयास करें:",
    tryAsk1: "क्योटो की 3-दिवसीय यात्रा की योजना बनाएं",
    tryAsk2: "बर्लिन में विंटेज स्टोर खोजें",
    tryAsk3: "साइबरपंक अवतार उत्पन्न करें",
    upcomingDrops: "आगामी ड्रॉप्स",
    viewAll: "सभी देखें",
    noTripsPlanned: "अभी तक कोई यात्रा की योजना नहीं है।",
    systemStatus: "सिस्टम की स्थिति",
    aetheriaCard: "एथेरिया कार्ड",
    balanceZero: "$0.00",
    upgradeToPremium: "प्रीमियम में अपग्रेड करें",
    unlockPremium: "सभी AI सिंथेसिस इंजन और प्रीमियम सुविधाओं को अनलॉक करें।",
    viewPlans: "योजनाएं देखें",
    bookingHub: "बुकिंग हब",
    flightsHotelsMore: "उड़ानें, होटल और बहुत कुछ",
    createTeaser: "एक टीज़र बनाएँ",
    generateTeaserDesc: "सोशल मीडिया पर साझा करने के लिए अपनी अगली यात्रा के लिए AI-जनरेटेड सिनेमाई ट्रेलर बनाएं।",
    generateVideo: "वीडियो उत्पन्न करें",
    spillTheTea: "राज खोलें।",
    logJournalEntry: "एक नई जर्नल प्रविष्टि लॉग करें।",
    brandAetheria: "AETHERIA",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    contact: "संपर्क करें",
    copyright: "© 2026 Aetheria Ecosystem. सर्वाधिकार सुरक्षित।"
  },
  id: {
    version: "Aetheria OS v2.0",
    readyTo: "Siap untuk",
    vibeCheck: "cek getaran dunia?",
    copilotStandby: "Co-pilot AI Anda sedang bersiap.",
    dropPin: "Tandai lokasi",
    aiItinerary: "Itinerary AI",
    vibeMarket: "Pasar Suasana",
    capture: "Tangkap",
    wallet: "Dompet",
    aiSynthesisEngine: "Mesin Sintesis AI",
    tellAetheria: "Beri tahu Aetheria apa yang ingin Anda lakukan...",
    synthesize: "Sintesis",
    tryAsking: "Coba tanyakan:",
    tryAsk1: "Rencanakan perjalanan 3 hari ke Kyoto",
    tryAsk2: "Temukan toko vintage di Berlin",
    tryAsk3: "Buat avatar cyberpunk",
    upcomingDrops: "Rilisan Mendatang",
    viewAll: "Lihat Semua",
    noTripsPlanned: "Belum ada rencana perjalanan.",
    systemStatus: "Status Sistem",
    aetheriaCard: "Kartu Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Tingkatkan ke Premium",
    unlockPremium: "Buka kunci semua mesin sintesis AI dan fitur premium.",
    viewPlans: "Lihat Paket",
    bookingHub: "Pusat Pemesanan",
    flightsHotelsMore: "Penerbangan, Hotel, & Lainnya",
    createTeaser: "Buat Teaser",
    generateTeaserDesc: "Hasilkan trailer sinematik AI untuk perjalanan Anda berikutnya.",
    generateVideo: "Hasilkan Video",
    spillTheTea: "Bagikan ceritanya.",
    logJournalEntry: "Catat entri jurnal baru.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Kebijakan Privasi",
    termsOfService: "Ketentuan Layanan",
    contact: "Kontak",
    copyright: "© 2026 Aetheria Ecosystem. Hak Cipta Dilindungi."
  },
  it: {
    version: "Aetheria OS v2.0",
    readyTo: "Pronto a",
    vibeCheck: "controllare le vibrazioni del mondo?",
    copilotStandby: "Il tuo co-pilota IA è pronto.",
    dropPin: "Lascia un segnaposto",
    aiItinerary: "Itinerario IA",
    vibeMarket: "Mercato dell'Atmosfera",
    capture: "Cattura",
    wallet: "Portafoglio",
    aiSynthesisEngine: "Motore di Sintesi IA",
    tellAetheria: "Dì ad Aetheria cosa vuoi fare...",
    synthesize: "Sintetizzare",
    tryAsking: "Prova a chiedere:",
    tryAsk1: "Pianifica un viaggio di 3 giorni a Kyoto",
    tryAsk2: "Trova negozi vintage a Berlino",
    tryAsk3: "Genera un avatar cyberpunk",
    upcomingDrops: "Prossimi Rilasci",
    viewAll: "Mostra Tutti",
    noTripsPlanned: "Nessun viaggio pianificato finora.",
    systemStatus: "Stato del Sistema",
    aetheriaCard: "Carta Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Passa a Premium",
    unlockPremium: "Sblocca tutti i motori di sintesi IA e le funzionalità premium.",
    viewPlans: "Visualizza Piani",
    bookingHub: "Centro Prenotazioni",
    flightsHotelsMore: "Voli, Hotel e Altro",
    createTeaser: "Crea un Teaser",
    generateTeaserDesc: "Genera con l'IA un trailer cinematografico del tuo prossimo viaggio.",
    generateVideo: "Genera Video",
    spillTheTea: "Racconta i pettegolezzi.",
    logJournalEntry: "Registra una nuova voce nel diario.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Informativa sulla Privacy",
    termsOfService: "Termini di Servizio",
    contact: "Contatto",
    copyright: "© 2026 Aetheria Ecosystem. Tutti i diritti riservati."
  },
  ja: {
    version: "Aetheria OS v2.0",
    readyTo: "準備はいいですか？",
    vibeCheck: "世界のバイブスをチェックする",
    copilotStandby: "AI副操縦士が待機中です。",
    dropPin: "ピンをドロップ",
    aiItinerary: "AI旅程",
    vibeMarket: "バイブマーケット",
    capture: "キャプチャ",
    wallet: "ウォレット",
    aiSynthesisEngine: "AI合成エンジン",
    tellAetheria: "Aetheriaにやりたいことを伝えてください...",
    synthesize: "合成する",
    tryAsking: "試してみてください:",
    tryAsk1: "京都への3日間の旅行を計画して",
    tryAsk2: "ベルリンのヴィンテージショップを見つけて",
    tryAsk3: "サイバーパンクのアバターを生成して",
    upcomingDrops: "今後のドロップ",
    viewAll: "すべて表示",
    noTripsPlanned: "まだ旅行の計画はありません。",
    systemStatus: "システムステータス",
    aetheriaCard: "Aetheriaカード",
    balanceZero: "$0.00",
    upgradeToPremium: "プレミアムにアップグレード",
    unlockPremium: "すべてのAI合成エンジンとプレミアム機能のロックを解除します。",
    viewPlans: "プランを見る",
    bookingHub: "予約ハブ",
    flightsHotelsMore: "航空券、ホテル、その他",
    createTeaser: "ティーザーを作成",
    generateTeaserDesc: "SNSで共有する次の旅行のシネマティックトレーラーをAIで生成します。",
    generateVideo: "ビデオを生成",
    spillTheTea: "秘密を教えて。",
    logJournalEntry: "新しいジャーナルエントリを記録します。",
    brandAetheria: "AETHERIA",
    privacyPolicy: "プライバシーポリシー",
    termsOfService: "利用規約",
    contact: "お問い合わせ",
    copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
  },
  kn: {
    version: "Aetheria OS v2.0",
    readyTo: "ಇದಕ್ಕೆ ಸಿದ್ಧರಿದ್ದೀರಾ",
    vibeCheck: "ಪ್ರಪಂಚದ ವೈಬ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ?",
    copilotStandby: "ನಿಮ್ಮ AI ಸಹ-ಪೈಲಟ್ ಸಿದ್ಧವಾಗಿದೆ.",
    dropPin: "ಪಿನ್ ಅನ್ನು ಬಿಡಿ",
    aiItinerary: "AI ಪ್ರವಾಸದ ಯೋಜನೆ",
    vibeMarket: "ವೈಬ್ ಮಾರ್ಕೆಟ್",
    capture: "ಕ್ಯಾಪ್ಚರ್",
    wallet: "ವಾಲೆಟ್",
    aiSynthesisEngine: "AI ಸಂಶ್ಲೇಷಣೆ ಎಂಜಿನ್",
    tellAetheria: "ನೀವು ಏನು ಮಾಡಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ಎಥೆರಿಯಾಗೆ ತಿಳಿಸಿ...",
    synthesize: "ಸಂಶ್ಲೇಷಿಸಿ",
    tryAsking: "ಹೀಗೆ ಕೇಳಲು ಪ್ರಯತ್ನಿಸಿ:",
    tryAsk1: "ಕ್ಯೋಟೋಗೆ 3-ದಿನದ ಪ್ರವಾಸವನ್ನು ಯೋಜಿಸಿ",
    tryAsk2: "ಬರ್ಲಿನ್‌ನಲ್ಲಿ ವಿಂಟೇಜ್ ಸ್ಟೋರ್‌ಗಳನ್ನು ಹುಡುಕಿ",
    tryAsk3: "ಸೈಬರ್‌ಪಂಕ್ ಅವತಾರವನ್ನು ರಚಿಸಿ",
    upcomingDrops: "ಮುಂಬರುವ ಬಿಡುಗಡೆಗಳು",
    viewAll: "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    noTripsPlanned: "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರವಾಸಗಳನ್ನು ಯೋಜಿಸಲಾಗಿಲ್ಲ.",
    systemStatus: "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ",
    aetheriaCard: "ಎಥೆರಿಯಾ ಕಾರ್ಡ್",
    balanceZero: "$0.00",
    upgradeToPremium: "ಪ್ರೀಮಿಯಂಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ",
    unlockPremium: "ಎಲ್ಲಾ AI ಸಂಶ್ಲೇಷಣೆ ಎಂಜಿನ್‌ಗಳು ಮತ್ತು ಪ್ರೀಮಿಯಂ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ.",
    viewPlans: "ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    bookingHub: "ಬುಕಿಂಗ್ ಹಬ್",
    flightsHotelsMore: "ವಿಮಾನಗಳು, ಹೋಟೆಲ್‌ಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು",
    createTeaser: "ಟೀಸರ್ ರಚಿಸಿ",
    generateTeaserDesc: "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಲು ನಿಮ್ಮ ಮುಂದಿನ ಪ್ರವಾಸಕ್ಕಾಗಿ ಸಿನಿಮೀಯ ಟ್ರೈಲರ್ ಅನ್ನು AI ನಿಂದ ರಚಿಸಿ.",
    generateVideo: "ವೀಡಿಯೊವನ್ನು ರಚಿಸಿ",
    spillTheTea: "ರಹಸ್ಯಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.",
    logJournalEntry: "ಹೊಸ ಜರ್ನಲ್ ನಮೂದನ್ನು ಲಾಗ್ ಮಾಡಿ.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "ಗೌಪ್ಯತೆ ನೀತಿ",
    termsOfService: "ಸೇವಾ ನಿಯಮಗಳು",
    contact: "ಸಂಪರ್ಕ",
    copyright: "© 2026 Aetheria Ecosystem. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ."
  },
  ml: {
    version: "Aetheria OS v2.0",
    readyTo: "തയ്യാറാണോ",
    vibeCheck: "ലോകത്തിന്റെ വൈബ് പരിശോധിക്കാൻ?",
    copilotStandby: "നിങ്ങളുടെ AI കോ-പൈലറ്റ് തയ്യാറാണ്.",
    dropPin: "ഒരു പിൻ ഡ്രോപ്പ് ചെയ്യുക",
    aiItinerary: "AI യാത്രാവിവരണം",
    vibeMarket: "വൈബ് മാർക്കറ്റ്",
    capture: "ക്യാപ്ചർ",
    wallet: "വാലറ്റ്",
    aiSynthesisEngine: "AI സിന്തസിസ് എഞ്ചിൻ",
    tellAetheria: "നിങ്ങൾക്ക് എന്താണ് ചെയ്യേണ്ടതെന്ന് എത്തേറിയയോട് പറയുക...",
    synthesize: "സിന്തസൈസ്",
    tryAsking: "ഇങ്ങനെ ചോദിക്കാൻ ശ്രമിക്കുക:",
    tryAsk1: "ക്യോട്ടോയിലേക്ക് 3 ദിവസത്തെ യാത്ര ആസൂത്രണം ചെയ്യുക",
    tryAsk2: "ബർലിനിൽ വിന്റേജ് സ്റ്റോറുകൾ കണ്ടെത്തുക",
    tryAsk3: "ഒരു സൈബർപങ്ക് അവതാരം ജനറേറ്റ് ചെയ്യുക",
    upcomingDrops: "വരാനിരിക്കുന്ന ഡ്രോപ്പുകൾ",
    viewAll: "എല്ലാം കാണുക",
    noTripsPlanned: "യാത്രകളൊന്നും പ്ലാൻ ചെയ്തിട്ടില്ല.",
    systemStatus: "സിസ്റ്റം സ്റ്റാറ്റസ്",
    aetheriaCard: "എത്തേറിയ കാർഡ്",
    balanceZero: "$0.00",
    upgradeToPremium: "പ്രീമിയത്തിലേക്ക് അപ്‌ഗ്രേഡ് ചെയ്യുക",
    unlockPremium: "എല്ലാ AI സിന്തസിസ് എഞ്ചിനുകളും പ്രീമിയം സവിശേഷതകളും അൺലോക്ക് ചെയ്യുക.",
    viewPlans: "പ്ലാനുകൾ കാണുക",
    bookingHub: "ബുക്കിംഗ് ഹബ്",
    flightsHotelsMore: "ഫ്ലൈറ്റുകൾ, ഹോട്ടലുകൾ, കൂടാതെ കൂടുതൽ",
    createTeaser: "ഒരു ടീസർ സൃഷ്ടിക്കുക",
    generateTeaserDesc: "സോഷ്യൽ മീഡിയയിൽ പങ്കിടുന്നതിന് നിങ്ങളുടെ അടുത്ത യാത്രയ്ക്കായി ഒരു സിനിമാറ്റിക് ട്രെയിലർ AI ജനറേറ്റ് ചെയ്യുക.",
    generateVideo: "വീഡിയോ ജനറേറ്റ് ചെയ്യുക",
    spillTheTea: "രഹസ്യങ്ങൾ പങ്കിടുക.",
    logJournalEntry: "ഒരു പുതിയ ജേണൽ എൻട്രി ലോഗ് ചെയ്യുക.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "സ്വകാര്യതാ നയം",
    termsOfService: "സേവന വ്യവസ്ഥകൾ",
    contact: "ബന്ധപ്പെടുക",
    copyright: "© 2026 Aetheria Ecosystem. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം."
  },
  ms: {
    version: "Aetheria OS v2.0",
    readyTo: "Sedia untuk",
    vibeCheck: "periksa suasana dunia?",
    copilotStandby: "Pembantu juruterbang AI anda sudah sedia.",
    dropPin: "Tandakan lokasi",
    aiItinerary: "Jadual AI",
    vibeMarket: "Pasar Suasana",
    capture: "Tangkap",
    wallet: "Dompet",
    aiSynthesisEngine: "Enjin Sintesis AI",
    tellAetheria: "Beritahu Aetheria apa yang anda mahu lakukan...",
    synthesize: "Sintesis",
    tryAsking: "Cuba tanya:",
    tryAsk1: "Rancang perjalanan 3 hari ke Kyoto",
    tryAsk2: "Cari kedai vintaj di Berlin",
    tryAsk3: "Jana avatar cyberpunk",
    upcomingDrops: "Keluaran Akan Datang",
    viewAll: "Lihat Semua",
    noTripsPlanned: "Tiada perjalanan dirancang lagi.",
    systemStatus: "Status Sistem",
    aetheriaCard: "Kad Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Tingkatkan ke Premium",
    unlockPremium: "Buka kunci semua enjin sintesis AI dan ciri premium.",
    viewPlans: "Lihat Pelan",
    bookingHub: "Pusat Tempahan",
    flightsHotelsMore: "Penerbangan, Hotel & Banyak Lagi",
    createTeaser: "Cipta Teaser",
    generateTeaserDesc: "Jana treler sinematik AI untuk perjalanan anda seterusnya.",
    generateVideo: "Jana Video",
    spillTheTea: "Kongsi cerita.",
    logJournalEntry: "Catat entri jurnal baru.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Dasar Privasi",
    termsOfService: "Syarat Perkhidmatan",
    contact: "Kenalan",
    copyright: "© 2026 Aetheria Ecosystem. Hak Cipta Terpelihara."
  },
  nl: {
    version: "Aetheria OS v2.0",
    readyTo: "Klaar om",
    vibeCheck: "de vibe van de wereld te checken?",
    copilotStandby: "Je AI-co-piloot staat paraat.",
    dropPin: "Plaats een speld",
    aiItinerary: "AI Reisroute",
    vibeMarket: "Vibe Markt",
    capture: "Vastleggen",
    wallet: "Portemonnee",
    aiSynthesisEngine: "AI Synthese Engine",
    tellAetheria: "Vertel Aetheria wat je wilt doen...",
    synthesize: "Synthetiseren",
    tryAsking: "Probeer te vragen:",
    tryAsk1: "Plan een 3-daagse trip naar Kyoto",
    tryAsk2: "Vind vintage winkels in Berlijn",
    tryAsk3: "Genereer een cyberpunk avatar",
    upcomingDrops: "Aankomende Drops",
    viewAll: "Alles bekijken",
    noTripsPlanned: "Nog geen reizen gepland.",
    systemStatus: "Systeemstatus",
    aetheriaCard: "Aetheria Kaart",
    balanceZero: "$0.00",
    upgradeToPremium: "Upgrade naar Premium",
    unlockPremium: "Ontgrendel alle AI-synthese-engines en premium functies.",
    viewPlans: "Plannen bekijken",
    bookingHub: "Boekingshub",
    flightsHotelsMore: "Vluchten, Hotels & Meer",
    createTeaser: "Maak een Teaser",
    generateTeaserDesc: "Genereer een AI-bioscooptrailer voor je volgende reis.",
    generateVideo: "Genereer Video",
    spillTheTea: "Vertel de roddels.",
    logJournalEntry: "Voer een nieuwe logboekinvoer in.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Privacybeleid",
    termsOfService: "Servicevoorwaarden",
    contact: "Contact",
    copyright: "© 2026 Aetheria Ecosystem. Alle rechten voorbehouden."
  },
  pcm: {
    version: "Aetheria OS v2.0",
    readyTo: "You ready to",
    vibeCheck: "check di vibe of di world?",
    copilotStandby: "Your AI co-pilot don ready.",
    dropPin: "Drop one pin",
    aiItinerary: "AI Itinerary",
    vibeMarket: "Vibe Market",
    capture: "Capture",
    wallet: "Wallet",
    aiSynthesisEngine: "AI Synthesis Engine",
    tellAetheria: "Tell Aetheria wetin you won do...",
    synthesize: "Synthesize",
    tryAsking: "Try ask:",
    tryAsk1: "Plan 3-day trip to Kyoto",
    tryAsk2: "Find vintage stores for Berlin",
    tryAsk3: "Generate cyberpunk avatar",
    upcomingDrops: "Upcoming Drops",
    viewAll: "View All",
    noTripsPlanned: "No trips planned yet.",
    systemStatus: "System Status",
    aetheriaCard: "Aetheria Card",
    balanceZero: "$0.00",
    upgradeToPremium: "Upgrade to Premium",
    unlockPremium: "Unlock all AI synthesis engines and premium features.",
    viewPlans: "View Plans",
    bookingHub: "Booking Hub",
    flightsHotelsMore: "Flights, Hotels, & More",
    createTeaser: "Create Teaser",
    generateTeaserDesc: "AI-generate cinematic trailer for your next trip to share.",
    generateVideo: "Generate Video",
    spillTheTea: "Spill di tea.",
    logJournalEntry: "Log new journal entry.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contact: "Contact",
    copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
  },
  pl: {
    version: "Aetheria OS v2.0",
    readyTo: "Gotowy na",
    vibeCheck: "sprawdzenie klimatu świata?",
    copilotStandby: "Twój drugi pilot AI jest gotowy.",
    dropPin: "Upuść pinezkę",
    aiItinerary: "Plan Podróży AI",
    vibeMarket: "Rynek Klimatów",
    capture: "Uchwyć",
    wallet: "Portfel",
    aiSynthesisEngine: "Silnik Syntezy AI",
    tellAetheria: "Powiedz Aetherii, co chcesz zrobić...",
    synthesize: "Syntetyzuj",
    tryAsking: "Spróbuj zapytać:",
    tryAsk1: "Zaplanuj 3-dniową wycieczkę do Kioto",
    tryAsk2: "Znajdź sklepy vintage w Berlinie",
    tryAsk3: "Wygeneruj awatara cyberpunk",
    upcomingDrops: "Nadchodzące nowości",
    viewAll: "Zobacz wszystko",
    noTripsPlanned: "Nie zaplanowano jeszcze żadnych wycieczek.",
    systemStatus: "Status Systemu",
    aetheriaCard: "Karta Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Ulepsz do Premium",
    unlockPremium: "Odblokuj wszystkie silniki syntezy AI i funkcje premium.",
    viewPlans: "Zobacz Plany",
    bookingHub: "Centrum Rezerwacji",
    flightsHotelsMore: "Loty, Hotele i Więcej",
    createTeaser: "Stwórz Zwiastun",
    generateTeaserDesc: "Wygeneruj kinowy zwiastun swojej następnej podróży.",
    generateVideo: "Wygeneruj Wideo",
    spillTheTea: "Opowiedz wszystko.",
    logJournalEntry: "Zapisz nowy wpis w dzienniku.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Polityka Prywatności",
    termsOfService: "Warunki Usługi",
    contact: "Kontakt",
    copyright: "© 2026 Aetheria Ecosystem. Wszelkie prawa zastrzeżone."
  },
  pt: {
    version: "Aetheria OS v2.0",
    readyTo: "Pronto para",
    vibeCheck: "verificar a vibração do mundo?",
    copilotStandby: "O seu co-piloto de IA está pronto.",
    dropPin: "Soltar um pino",
    aiItinerary: "Itinerário com IA",
    vibeMarket: "Mercado de Vibrações",
    capture: "Capturar",
    wallet: "Carteira",
    aiSynthesisEngine: "Motor de Síntese de IA",
    tellAetheria: "Diga à Aetheria o que você quer fazer...",
    synthesize: "Sintetizar",
    tryAsking: "Tente perguntar:",
    tryAsk1: "Planeie uma viagem de 3 dias para Quioto",
    tryAsk2: "Encontre lojas vintage em Berlim",
    tryAsk3: "Gere um avatar cyberpunk",
    upcomingDrops: "Próximos Lançamentos",
    viewAll: "Ver Todos",
    noTripsPlanned: "Nenhuma viagem planeada ainda.",
    systemStatus: "Estado do Sistema",
    aetheriaCard: "Cartão Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Atualizar para Premium",
    unlockPremium: "Desbloqueie todos os motores de síntese de IA e recursos premium.",
    viewPlans: "Ver Planos",
    bookingHub: "Centro de Reservas",
    flightsHotelsMore: "Voos, Hotéis e Mais",
    createTeaser: "Criar um Teaser",
    generateTeaserDesc: "Gere um trailer cinematográfico da sua próxima viagem.",
    generateVideo: "Gerar Vídeo",
    spillTheTea: "Conte a fofoca.",
    logJournalEntry: "Registre uma nova entrada no diário.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    contact: "Contacto",
    copyright: "© 2026 Aetheria Ecosystem. Todos os direitos reservados."
  },
  ru: {
    version: "Aetheria OS v2.0",
    readyTo: "Готовы",
    vibeCheck: "проверить атмосферу мира?",
    copilotStandby: "Ваш ИИ-второй пилот готов.",
    dropPin: "Поставить метку",
    aiItinerary: "ИИ Маршрут",
    vibeMarket: "Рынок атмосферы",
    capture: "Захват",
    wallet: "Кошелек",
    aiSynthesisEngine: "Механизм ИИ Синтеза",
    tellAetheria: "Скажите Aetheria, что вы хотите сделать...",
    synthesize: "Синтезировать",
    tryAsking: "Попробуйте спросить:",
    tryAsk1: "Спланируй 3-дневную поездку в Киото",
    tryAsk2: "Найди винтажные магазины в Берлине",
    tryAsk3: "Сгенерируй киберпанк аватар",
    upcomingDrops: "Предстоящие релизы",
    viewAll: "Смотреть все",
    noTripsPlanned: "Пока нет запланированных поездок.",
    systemStatus: "Статус системы",
    aetheriaCard: "Карта Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Перейти на Premium",
    unlockPremium: "Разблокируйте все механизмы ИИ и премиум-функции.",
    viewPlans: "Смотреть планы",
    bookingHub: "Центр бронирования",
    flightsHotelsMore: "Авиабилеты, Отели и многое другое",
    createTeaser: "Создать тизер",
    generateTeaserDesc: "Сгенерируйте кинематографический трейлер вашей следующей поездки.",
    generateVideo: "Сгенерировать видео",
    spillTheTea: "Расскажи секреты.",
    logJournalEntry: "Сделать новую запись в журнале.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Условия использования",
    contact: "Контакты",
    copyright: "© 2026 Aetheria Ecosystem. Все права защищены."
  },
  ta: {
    version: "Aetheria OS v2.0",
    readyTo: "நீங்கள் தயாரா",
    vibeCheck: "உலகின் சூழ்நிலையை சரிபார்க்க?",
    copilotStandby: "உங்கள் AI இணை பைலட் தயாராக உள்ளார்.",
    dropPin: "ஒரு பின்னை விடுங்கள்",
    aiItinerary: "AI பயண திட்டம்",
    vibeMarket: "வைப் சந்தை",
    capture: "படம் பிடி",
    wallet: "வாலட்",
    aiSynthesisEngine: "AI தொகுப்பு இயந்திரம்",
    tellAetheria: "நீங்கள் என்ன செய்ய விரும்புகிறீர்கள் என்று Aetheria இடம் சொல்லுங்கள்...",
    synthesize: "தொகுக்கவும்",
    tryAsking: "இவ்வாறு கேட்க முயற்சிக்கவும்:",
    tryAsk1: "கியோட்டோவிற்கு 3 நாள் பயணத்தை திட்டமிடுங்கள்",
    tryAsk2: "பெர்லினில் விண்டேஜ் கடைகளைக் கண்டறியவும்",
    tryAsk3: "சைபர்பங்க் அவதாரத்தை உருவாக்கவும்",
    upcomingDrops: "வரவிருக்கும் வெளியீடுகள்",
    viewAll: "அனைத்தையும் காண்க",
    noTripsPlanned: "இதுவரை எந்த பயணங்களும் திட்டமிடப்படவில்லை.",
    systemStatus: "கணினி நிலை",
    aetheriaCard: "Aetheria கார்டு",
    balanceZero: "$0.00",
    upgradeToPremium: "பிரீமியத்திற்கு மேம்படுத்தவும்",
    unlockPremium: "அனைத்து AI தொகுப்பு இயந்திரங்களையும் பிரீமியம் அம்சங்களையும் திறக்கவும்.",
    viewPlans: "திட்டங்களைக் காண்க",
    bookingHub: "முன்பதிவு மையம்",
    flightsHotelsMore: "விமானங்கள், ஹோட்டல்கள் & மேலும்",
    createTeaser: "ஒரு டீஸரை உருவாக்கவும்",
    generateTeaserDesc: "சமூக ஊடகங்களில் பகிர உங்கள் அடுத்த பயணத்திற்கான சினிமா டிரெய்லரை AI உருவாக்குகிறது.",
    generateVideo: "வீடியோவை உருவாக்குங்கள்",
    spillTheTea: "ரகசியங்களை பகிர்ந்துகொள்.",
    logJournalEntry: "ஒரு புதிய பத்திரிகை உள்ளீட்டை பதிவு செய்யவும்.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    termsOfService: "சேவை விதிமுறைகள்",
    contact: "தொடர்பு",
    copyright: "© 2026 Aetheria Ecosystem. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை."
  },
  te: {
    version: "Aetheria OS v2.0",
    readyTo: "దీనికి సిద్ధంగా ఉన్నారా",
    vibeCheck: "ప్రపంచం యొక్క వైబ్ తనిఖీ చేయాలా?",
    copilotStandby: "మీ AI సహ-పైలట్ సిద్ధంగా ఉన్నారు.",
    dropPin: "పిన్‌ను ఉంచండి",
    aiItinerary: "AI ప్రయాణ ప్రణాళిక",
    vibeMarket: "వైబ్ మార్కెట్",
    capture: "క్యాప్చర్",
    wallet: "వాలెట్",
    aiSynthesisEngine: "AI సింథసిస్ ఇంజిన్",
    tellAetheria: "మీరు ఏమి చేయాలనుకుంటున్నారో Aetheria కి చెప్పండి...",
    synthesize: "సింథసైజ్",
    tryAsking: "ఇలా అడగడానికి ప్రయత్నించండి:",
    tryAsk1: "క్యోటోకు 3 రోజుల పర్యటనను ప్లాన్ చేయండి",
    tryAsk2: "బెర్లిన్‌లో పాతకాలపు దుకాణాలను కనుగొనండి",
    tryAsk3: "సైబర్‌పంక్ అవతార్‌ను రూపొందించండి",
    upcomingDrops: "రాబోయే విడుదలలు",
    viewAll: "అన్నీ చూడండి",
    noTripsPlanned: "ఇంకా పర్యటనలు ప్లాన్ చేయబడలేదు.",
    systemStatus: "సిస్టమ్ స్థితి",
    aetheriaCard: "ఎథెరియా కార్డ్",
    balanceZero: "$0.00",
    upgradeToPremium: "ప్రీమియంకు అప్‌గ్రేడ్ చేయండి",
    unlockPremium: "అన్ని AI సింథసిస్ ఇంజిన్‌లను మరియు ప్రీమియం లక్షణాలను అన్‌లాక్ చేయండి.",
    viewPlans: "ప్లాన్‌లను చూడండి",
    bookingHub: "బుకింగ్ హబ్",
    flightsHotelsMore: "విమానాలు, హోటళ్లు & మరిన్ని",
    createTeaser: "టీజర్‌ని సృష్టించండి",
    generateTeaserDesc: "సోషల్ మీడియాలో భాగస్వామ్యం చేయడానికి మీ తదుపరి పర్యటన కోసం AI సినిమా ట్రైలర్‌ను సృష్టిస్తుంది.",
    generateVideo: "వీడియోను రూపొందించండి",
    spillTheTea: "రహస్యాలు చెప్పండి.",
    logJournalEntry: "కొత్త జర్నల్ ఎంట్రీని నమోదు చేయండి.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "గోప్యతా విధానం",
    termsOfService: "సేవా నిబంధనలు",
    contact: "సంప్రదించండి",
    copyright: "© 2026 Aetheria Ecosystem. సర్వ హక్కులు ప్రత్యేకించబడినవి."
  },
  tl: {
    version: "Aetheria OS v2.0",
    readyTo: "Handa na para",
    vibeCheck: "i-vibe check ang mundo?",
    copilotStandby: "Nakabantay ang iyong AI co-pilot.",
    dropPin: "Maghulog ng pin",
    aiItinerary: "AI Itinerary",
    vibeMarket: "Vibe Market",
    capture: "Kumuha",
    wallet: "Wallet",
    aiSynthesisEngine: "AI Synthesis Engine",
    tellAetheria: "Sabihin kay Aetheria kung ano ang gusto mong gawin...",
    synthesize: "Sintesisin",
    tryAsking: "Subukang itanong:",
    tryAsk1: "Magplano ng 3-araw na biyahe sa Kyoto",
    tryAsk2: "Humanap ng mga vintage store sa Berlin",
    tryAsk3: "Gumawa ng cyberpunk avatar",
    upcomingDrops: "Mga Paparating na Labas",
    viewAll: "Tingnan Lahat",
    noTripsPlanned: "Wala pang nakaplanong biyahe.",
    systemStatus: "Status ng System",
    aetheriaCard: "Aetheria Card",
    balanceZero: "$0.00",
    upgradeToPremium: "Mag-upgrade sa Premium",
    unlockPremium: "I-unlock ang lahat ng AI synthesis engine at mga premium na feature.",
    viewPlans: "Tingnan ang Mga Plano",
    bookingHub: "Booking Hub",
    flightsHotelsMore: "Mga Flight, Hotel, at Iba Pa",
    createTeaser: "Gumawa ng Teaser",
    generateTeaserDesc: "AI-bumuo ng cinematic trailer para sa iyong susunod na biyahe.",
    generateVideo: "Bumuo ng Video",
    spillTheTea: "Ikwento mo na.",
    logJournalEntry: "Mag-log ng bagong journal entry.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Patakaran sa Privacy",
    termsOfService: "Mga Tuntunin ng Serbisyo",
    contact: "Makipag-ugnayan",
    copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
  },
  tr: {
    version: "Aetheria OS v2.0",
    readyTo: "Dünyanın atmosferini",
    vibeCheck: "kontrol etmeye hazır mısın?",
    copilotStandby: "Yapay zeka yardımcı pilotunuz hazır.",
    dropPin: "Pin bırak",
    aiItinerary: "Yapay Zeka Rotası",
    vibeMarket: "Atmosfer Pazarı",
    capture: "Yakala",
    wallet: "Cüzdan",
    aiSynthesisEngine: "Yapay Zeka Sentez Motoru",
    tellAetheria: "Aetheria'ya ne yapmak istediğinizi söyleyin...",
    synthesize: "Sentezle",
    tryAsking: "Şunu sormayı deneyin:",
    tryAsk1: "Kyoto'ya 3 günlük bir gezi planla",
    tryAsk2: "Berlin'deki vintage mağazaları bul",
    tryAsk3: "Bir cyberpunk avatarı oluştur",
    upcomingDrops: "Yaklaşan Yayınlar",
    viewAll: "Tümünü Gör",
    noTripsPlanned: "Henüz planlanmış gezi yok.",
    systemStatus: "Sistem Durumu",
    aetheriaCard: "Aetheria Kartı",
    balanceZero: "$0.00",
    upgradeToPremium: "Premium'a Yükselt",
    unlockPremium: "Tüm yapay zeka sentez motorlarının ve premium özelliklerin kilidini açın.",
    viewPlans: "Planları Görüntüle",
    bookingHub: "Rezervasyon Merkezi",
    flightsHotelsMore: "Uçuşlar, Oteller ve Daha Fazlası",
    createTeaser: "Bir Fragman Oluştur",
    generateTeaserDesc: "Bir sonraki seyahatiniz için yapay zeka ile sinematik bir fragman oluşturun.",
    generateVideo: "Video Oluştur",
    spillTheTea: "Dedikoduları dök.",
    logJournalEntry: "Yeni bir günlük girişi günlüğe kaydet.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Gizlilik Politikası",
    termsOfService: "Hizmet Şartları",
    contact: "İletişim",
    copyright: "© 2026 Aetheria Ecosystem. Tüm hakları saklıdır."
  },
  ur: {
    version: "Aetheria OS v2.0",
    readyTo: "کیا آپ تیار ہیں",
    vibeCheck: "دنیا کا وائب چیک کرنے کے لیے؟",
    copilotStandby: "آپ کا AI شریک پائلٹ تیار ہے۔",
    dropPin: "ایک پن چھوڑیں",
    aiItinerary: "AI سفری نامہ",
    vibeMarket: "وائب مارکیٹ",
    capture: "کیپچر کریں",
    wallet: "والیٹ",
    aiSynthesisEngine: "AI سنتھیسس انجن",
    tellAetheria: "Aetheria کو بتائیں کہ آپ کیا کرنا چاہتے ہیں...",
    synthesize: "سنتھیسائز",
    tryAsking: "یہ پوچھنے کی کوشش کریں:",
    tryAsk1: "کیوٹو کے 3 دن کے سفر کی منصوبہ بندی کریں",
    tryAsk2: "برلن میں ونٹیج اسٹورز تلاش کریں",
    tryAsk3: "سائبر پنک اوتار بنائیں",
    upcomingDrops: "آنے والے ڈراپس",
    viewAll: "سب دیکھیں",
    noTripsPlanned: "ابھی تک کوئی سفر کا منصوبہ نہیں ہے۔",
    systemStatus: "سسٹم کی حیثیت",
    aetheriaCard: "ایتھیریا کارڈ",
    balanceZero: "$0.00",
    upgradeToPremium: "پریمیم میں اپ گریڈ کریں",
    unlockPremium: "تمام AI سنتھیسس انجن اور پریمیم خصوصیات کو غیر مقفل کریں۔",
    viewPlans: "منصوبے دیکھیں",
    bookingHub: "بکنگ ہب",
    flightsHotelsMore: "پروازیں، ہوٹل، اور مزید",
    createTeaser: "ایک ٹیزر بنائیں",
    generateTeaserDesc: "اپنے اگلے سفر کے لیے ایک AI سے تیار کردہ سنیما ٹریلر بنائیں۔",
    generateVideo: "ویڈیو بنائیں",
    spillTheTea: "راز کھولیں۔",
    logJournalEntry: "نئے جریدے کا اندراج لاگ کریں۔",
    brandAetheria: "AETHERIA",
    privacyPolicy: "رازداری کی پالیسی",
    termsOfService: "سروس کی شرائط",
    contact: "رابطہ کریں",
    copyright: "© 2026 Aetheria Ecosystem. جملہ حقوق محفوظ ہیں۔"
  },
  zh: {
    version: "Aetheria OS v2.0",
    readyTo: "准备好",
    vibeCheck: "感受世界氛围了吗？",
    copilotStandby: "您的 AI 副驾驶已就绪。",
    dropPin: "放置图钉",
    aiItinerary: "AI 行程",
    vibeMarket: "氛围市场",
    capture: "捕捉",
    wallet: "钱包",
    aiSynthesisEngine: "AI 合成引擎",
    tellAetheria: "告诉 Aetheria 你想做什么...",
    synthesize: "合成",
    tryAsking: "尝试提问：",
    tryAsk1: "规划一次去京都的 3 天旅行",
    tryAsk2: "在柏林寻找复古商店",
    tryAsk3: "生成一个赛博朋克化身",
    upcomingDrops: "即将发布",
    viewAll: "查看全部",
    noTripsPlanned: "暂无行程计划。",
    systemStatus: "系统状态",
    aetheriaCard: "Aetheria 卡",
    balanceZero: "$0.00",
    upgradeToPremium: "升级到高级版",
    unlockPremium: "解锁所有 AI 合成引擎和高级功能。",
    viewPlans: "查看计划",
    bookingHub: "预订中心",
    flightsHotelsMore: "航班、酒店及更多",
    createTeaser: "创建预告片",
    generateTeaserDesc: "为您的下一次旅行生成 AI 电影预告片以在社交媒体上分享。",
    generateVideo: "生成视频",
    spillTheTea: "八卦一下。",
    logJournalEntry: "记录一篇新日记。",
    brandAetheria: "AETHERIA",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    contact: "联系我们",
    copyright: "© 2026 Aetheria Ecosystem。保留所有权利。"
  }
};

const langs = Object.keys(translations);

for (const lang of langs) {
  const filePath = path.join(localesDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    
    // ensure 'os' namespace exists
    if (!data.os) {
      data.os = {};
    }
    
    // update strings
    const osTrans = translations[lang];
    for (const key of Object.keys(osTrans)) {
      data.os[key] = osTrans[key];
    }
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated OS strings in ${lang}.json`);
  }
}
