const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');

const enOs = {
  version: "Aetheria OS v2.0",
  readyTo: "Ready to",
  vibeCheck: "vibe check the world?",
  copilotStandby: "Your AI co-pilot is standing by.",
  dropPin: "Drop a pin",
  aiItinerary: "AI Itinerary",
  vibeMarket: "Vibe Market",
  capture: "Capture",
  wallet: "Wallet",
  aiSynthesisEngine: "AI Synthesis Engine",
  tellAetheria: "Tell Aetheria what you want to do...",
  synthesize: "Synthesize",
  tryAsking: "Try asking:",
  tryAsk1: "Plan a 3-day trip to Kyoto",
  tryAsk2: "Find vintage stores in Berlin",
  tryAsk3: "Generate a cyberpunk avatar",
  upcomingDrops: "Upcoming Drops",
  viewAll: "View All",
  noTripsPlanned: "No trips planned yet.",
  systemStatus: "System Status",
  aetheriaCard: "Aetheria Card",
  balanceZero: "$0.00",
  upgradeToPremium: "Upgrade to Premium",
  unlockPremium: "Unlock all AI synthesis engines and premium features.",
  viewPlans: "View Plans",
  bookingHub: "Booking Hub",
  flightsHotelsMore: "Flights, Hotels, & More",
  createTeaser: "Create a Teaser",
  generateTeaserDesc: "AI-generate a cinematic trailer for your next trip to share on socials.",
  generateVideo: "Generate Video",
  spillTheTea: "Spill the tea.",
  logJournalEntry: "Log a new journal entry.",
  brandAetheria: "AETHERIA",
  privacyPolicy: "Privacy Policy",
  termsOfService: "Terms of Service",
  contact: "Contact",
  copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
};

const translations = {
  id: {
    version: "Aetheria OS v2.0",
    readyTo: "Siap untuk",
    vibeCheck: "cek getaran dunia?",
    copilotStandby: "Co-pilot AI Anda sedang bersiap.",
    dropPin: "Tandai lokasi",
    aiItinerary: "Itinerary AI",
    vibeMarket: "Pasar Suasana",
    capture: "Tangkap",
    wallet: "Dompet",
    aiSynthesisEngine: "Mesin Sintesis AI",
    tellAetheria: "Beri tahu Aetheria apa yang ingin Anda lakukan...",
    synthesize: "Sintesis",
    tryAsking: "Coba tanyakan:",
    tryAsk1: "Rencanakan perjalanan 3 hari ke Kyoto",
    tryAsk2: "Temukan toko vintage di Berlin",
    tryAsk3: "Buat avatar cyberpunk",
    upcomingDrops: "Rilisan Mendatang",
    viewAll: "Lihat Semua",
    noTripsPlanned: "Belum ada rencana perjalanan.",
    systemStatus: "Status Sistem",
    aetheriaCard: "Kartu Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Tingkatkan ke Premium",
    unlockPremium: "Buka kunci semua mesin sintesis AI dan fitur premium.",
    viewPlans: "Lihat Paket",
    bookingHub: "Pusat Pemesanan",
    flightsHotelsMore: "Penerbangan, Hotel, & Lainnya",
    createTeaser: "Buat Teaser",
    generateTeaserDesc: "Hasilkan trailer sinematik AI untuk perjalanan Anda berikutnya.",
    generateVideo: "Hasilkan Video",
    spillTheTea: "Bagikan ceritanya.",
    logJournalEntry: "Catat entri jurnal baru.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Kebijakan Privasi",
    termsOfService: "Ketentuan Layanan",
    contact: "Kontak",
    copyright: "© 2026 Aetheria Ecosystem. Hak Cipta Dilindungi."
  },
  nl: {
    version: "Aetheria OS v2.0",
    readyTo: "Klaar om",
    vibeCheck: "de vibe van de wereld te checken?",
    copilotStandby: "Je AI-co-piloot staat paraat.",
    dropPin: "Plaats een speld",
    aiItinerary: "AI Reisroute",
    vibeMarket: "Vibe Markt",
    capture: "Vastleggen",
    wallet: "Portemonnee",
    aiSynthesisEngine: "AI Synthese Engine",
    tellAetheria: "Vertel Aetheria wat je wilt doen...",
    synthesize: "Synthetiseren",
    tryAsking: "Probeer te vragen:",
    tryAsk1: "Plan een 3-daagse trip naar Kyoto",
    tryAsk2: "Vind vintage winkels in Berlijn",
    tryAsk3: "Genereer een cyberpunk avatar",
    upcomingDrops: "Aankomende Drops",
    viewAll: "Alles bekijken",
    noTripsPlanned: "Nog geen reizen gepland.",
    systemStatus: "Systeemstatus",
    aetheriaCard: "Aetheria Kaart",
    balanceZero: "$0.00",
    upgradeToPremium: "Upgrade naar Premium",
    unlockPremium: "Ontgrendel alle AI-synthese-engines en premium functies.",
    viewPlans: "Plannen bekijken",
    bookingHub: "Boekingshub",
    flightsHotelsMore: "Vluchten, Hotels & Meer",
    createTeaser: "Maak een Teaser",
    generateTeaserDesc: "Genereer een AI-bioscooptrailer voor je volgende reis.",
    generateVideo: "Genereer Video",
    spillTheTea: "Vertel de roddels.",
    logJournalEntry: "Voer een nieuwe logboekinvoer in.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Privacybeleid",
    termsOfService: "Servicevoorwaarden",
    contact: "Contact",
    copyright: "© 2026 Aetheria Ecosystem. Alle rechten voorbehouden."
  },
  ms: {
    version: "Aetheria OS v2.0",
    readyTo: "Sedia untuk",
    vibeCheck: "periksa suasana dunia?",
    copilotStandby: "Pembantu juruterbang AI anda sudah sedia.",
    dropPin: "Tandakan lokasi",
    aiItinerary: "Jadual AI",
    vibeMarket: "Pasar Suasana",
    capture: "Tangkap",
    wallet: "Dompet",
    aiSynthesisEngine: "Enjin Sintesis AI",
    tellAetheria: "Beritahu Aetheria apa yang anda mahu lakukan...",
    synthesize: "Sintesis",
    tryAsking: "Cuba tanya:",
    tryAsk1: "Rancang perjalanan 3 hari ke Kyoto",
    tryAsk2: "Cari kedai vintaj di Berlin",
    tryAsk3: "Jana avatar cyberpunk",
    upcomingDrops: "Keluaran Akan Datang",
    viewAll: "Lihat Semua",
    noTripsPlanned: "Tiada perjalanan dirancang lagi.",
    systemStatus: "Status Sistem",
    aetheriaCard: "Kad Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Tingkatkan ke Premium",
    unlockPremium: "Buka kunci semua enjin sintesis AI dan ciri premium.",
    viewPlans: "Lihat Pelan",
    bookingHub: "Pusat Tempahan",
    flightsHotelsMore: "Penerbangan, Hotel & Banyak Lagi",
    createTeaser: "Cipta Teaser",
    generateTeaserDesc: "Jana treler sinematik AI untuk perjalanan anda seterusnya.",
    generateVideo: "Jana Video",
    spillTheTea: "Kongsi cerita.",
    logJournalEntry: "Catat entri jurnal baru.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Dasar Privasi",
    termsOfService: "Syarat Perkhidmatan",
    contact: "Kenalan",
    copyright: "© 2026 Aetheria Ecosystem. Hak Cipta Terpelihara."
  },
  pcm: {
    version: "Aetheria OS v2.0",
    readyTo: "You ready to",
    vibeCheck: "check di vibe of di world?",
    copilotStandby: "Your AI co-pilot don ready.",
    dropPin: "Drop one pin",
    aiItinerary: "AI Itinerary",
    vibeMarket: "Vibe Market",
    capture: "Capture",
    wallet: "Wallet",
    aiSynthesisEngine: "AI Synthesis Engine",
    tellAetheria: "Tell Aetheria wetin you won do...",
    synthesize: "Synthesize",
    tryAsking: "Try ask:",
    tryAsk1: "Plan 3-day trip to Kyoto",
    tryAsk2: "Find vintage stores for Berlin",
    tryAsk3: "Generate cyberpunk avatar",
    upcomingDrops: "Upcoming Drops",
    viewAll: "View All",
    noTripsPlanned: "No trips planned yet.",
    systemStatus: "System Status",
    aetheriaCard: "Aetheria Card",
    balanceZero: "$0.00",
    upgradeToPremium: "Upgrade to Premium",
    unlockPremium: "Unlock all AI synthesis engines and premium features.",
    viewPlans: "View Plans",
    bookingHub: "Booking Hub",
    flightsHotelsMore: "Flights, Hotels, & More",
    createTeaser: "Create Teaser",
    generateTeaserDesc: "AI-generate cinematic trailer for your next trip to share.",
    generateVideo: "Generate Video",
    spillTheTea: "Spill di tea.",
    logJournalEntry: "Log new journal entry.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    contact: "Contact",
    copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
  },
  pl: {
    version: "Aetheria OS v2.0",
    readyTo: "Gotowy na",
    vibeCheck: "sprawdzenie klimatu świata?",
    copilotStandby: "Twój drugi pilot AI jest gotowy.",
    dropPin: "Upuść pinezkę",
    aiItinerary: "Plan Podróży AI",
    vibeMarket: "Rynek Klimatów",
    capture: "Uchwyć",
    wallet: "Portfel",
    aiSynthesisEngine: "Silnik Syntezy AI",
    tellAetheria: "Powiedz Aetherii, co chcesz zrobić...",
    synthesize: "Syntetyzuj",
    tryAsking: "Spróbuj zapytać:",
    tryAsk1: "Zaplanuj 3-dniową wycieczkę do Kioto",
    tryAsk2: "Znajdź sklepy vintage w Berlinie",
    tryAsk3: "Wygeneruj awatara cyberpunk",
    upcomingDrops: "Nadchodzące nowości",
    viewAll: "Zobacz wszystko",
    noTripsPlanned: "Nie zaplanowano jeszcze żadnych wycieczek.",
    systemStatus: "Status Systemu",
    aetheriaCard: "Karta Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Ulepsz do Premium",
    unlockPremium: "Odblokuj wszystkie silniki syntezy AI i funkcje premium.",
    viewPlans: "Zobacz Plany",
    bookingHub: "Centrum Rezerwacji",
    flightsHotelsMore: "Loty, Hotele i Więcej",
    createTeaser: "Stwórz Zwiastun",
    generateTeaserDesc: "Wygeneruj kinowy zwiastun swojej następnej podróży.",
    generateVideo: "Wygeneruj Wideo",
    spillTheTea: "Opowiedz wszystko.",
    logJournalEntry: "Zapisz nowy wpis w dzienniku.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Polityka Prywatności",
    termsOfService: "Warunki Usługi",
    contact: "Kontakt",
    copyright: "© 2026 Aetheria Ecosystem. Wszelkie prawa zastrzeżone."
  },
  pt: {
    version: "Aetheria OS v2.0",
    readyTo: "Pronto para",
    vibeCheck: "verificar a vibração do mundo?",
    copilotStandby: "O seu co-piloto de IA está pronto.",
    dropPin: "Soltar um pino",
    aiItinerary: "Itinerário com IA",
    vibeMarket: "Mercado de Vibrações",
    capture: "Capturar",
    wallet: "Carteira",
    aiSynthesisEngine: "Motor de Síntese de IA",
    tellAetheria: "Diga à Aetheria o que você quer fazer...",
    synthesize: "Sintetizar",
    tryAsking: "Tente perguntar:",
    tryAsk1: "Planeie uma viagem de 3 dias para Quioto",
    tryAsk2: "Encontre lojas vintage em Berlim",
    tryAsk3: "Gere um avatar cyberpunk",
    upcomingDrops: "Próximos Lançamentos",
    viewAll: "Ver Todos",
    noTripsPlanned: "Nenhuma viagem planeada ainda.",
    systemStatus: "Estado do Sistema",
    aetheriaCard: "Cartão Aetheria",
    balanceZero: "$0.00",
    upgradeToPremium: "Atualizar para Premium",
    unlockPremium: "Desbloqueie todos os motores de síntese de IA e recursos premium.",
    viewPlans: "Ver Planos",
    bookingHub: "Centro de Reservas",
    flightsHotelsMore: "Voos, Hotéis e Mais",
    createTeaser: "Criar um Teaser",
    generateTeaserDesc: "Gere um trailer cinematográfico da sua próxima viagem.",
    generateVideo: "Gerar Vídeo",
    spillTheTea: "Conte a fofoca.",
    logJournalEntry: "Registre uma nova entrada no diário.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Política de Privacidade",
    termsOfService: "Termos de Serviço",
    contact: "Contacto",
    copyright: "© 2026 Aetheria Ecosystem. Todos os direitos reservados."
  },
  tl: {
    version: "Aetheria OS v2.0",
    readyTo: "Handa na para",
    vibeCheck: "i-vibe check ang mundo?",
    copilotStandby: "Nakabantay ang iyong AI co-pilot.",
    dropPin: "Maghulog ng pin",
    aiItinerary: "AI Itinerary",
    vibeMarket: "Vibe Market",
    capture: "Kumuha",
    wallet: "Wallet",
    aiSynthesisEngine: "AI Synthesis Engine",
    tellAetheria: "Sabihin kay Aetheria kung ano ang gusto mong gawin...",
    synthesize: "Sintesisin",
    tryAsking: "Subukang itanong:",
    tryAsk1: "Magplano ng 3-araw na biyahe sa Kyoto",
    tryAsk2: "Humanap ng mga vintage store sa Berlin",
    tryAsk3: "Gumawa ng cyberpunk avatar",
    upcomingDrops: "Mga Paparating na Labas",
    viewAll: "Tingnan Lahat",
    noTripsPlanned: "Wala pang nakaplanong biyahe.",
    systemStatus: "Status ng System",
    aetheriaCard: "Aetheria Card",
    balanceZero: "$0.00",
    upgradeToPremium: "Mag-upgrade sa Premium",
    unlockPremium: "I-unlock ang lahat ng AI synthesis engine at mga premium na feature.",
    viewPlans: "Tingnan ang Mga Plano",
    bookingHub: "Booking Hub",
    flightsHotelsMore: "Mga Flight, Hotel, at Iba Pa",
    createTeaser: "Gumawa ng Teaser",
    generateTeaserDesc: "AI-bumuo ng cinematic trailer para sa iyong susunod na biyahe.",
    generateVideo: "Bumuo ng Video",
    spillTheTea: "Ikwento mo na.",
    logJournalEntry: "Mag-log ng bagong journal entry.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Patakaran sa Privacy",
    termsOfService: "Mga Tuntunin ng Serbisyo",
    contact: "Makipag-ugnayan",
    copyright: "© 2026 Aetheria Ecosystem. All rights reserved."
  },
  tr: {
    version: "Aetheria OS v2.0",
    readyTo: "Dünyanın atmosferini",
    vibeCheck: "kontrol etmeye hazır mısın?",
    copilotStandby: "Yapay zeka yardımcı pilotunuz hazır.",
    dropPin: "Pin bırak",
    aiItinerary: "Yapay Zeka Rotası",
    vibeMarket: "Atmosfer Pazarı",
    capture: "Yakala",
    wallet: "Cüzdan",
    aiSynthesisEngine: "Yapay Zeka Sentez Motoru",
    tellAetheria: "Aetheria'ya ne yapmak istediğinizi söyleyin...",
    synthesize: "Sentezle",
    tryAsking: "Şunu sormayı deneyin:",
    tryAsk1: "Kyoto'ya 3 günlük bir gezi planla",
    tryAsk2: "Berlin'deki vintage mağazaları bul",
    tryAsk3: "Bir cyberpunk avatarı oluştur",
    upcomingDrops: "Yaklaşan Yayınlar",
    viewAll: "Tümünü Gör",
    noTripsPlanned: "Henüz planlanmış gezi yok.",
    systemStatus: "Sistem Durumu",
    aetheriaCard: "Aetheria Kartı",
    balanceZero: "$0.00",
    upgradeToPremium: "Premium'a Yükselt",
    unlockPremium: "Tüm yapay zeka sentez motorlarının ve premium özelliklerin kilidini açın.",
    viewPlans: "Planları Görüntüle",
    bookingHub: "Rezervasyon Merkezi",
    flightsHotelsMore: "Uçuşlar, Oteller ve Daha Fazlası",
    createTeaser: "Bir Fragman Oluştur",
    generateTeaserDesc: "Bir sonraki seyahatiniz için yapay zeka ile sinematik bir fragman oluşturun.",
    generateVideo: "Video Oluştur",
    spillTheTea: "Dedikoduları dök.",
    logJournalEntry: "Yeni bir günlük girişi günlüğe kaydet.",
    brandAetheria: "AETHERIA",
    privacyPolicy: "Gizlilik Politikası",
    termsOfService: "Hizmet Şartları",
    contact: "İletişim",
    copyright: "© 2026 Aetheria Ecosystem. Tüm hakları saklıdır."
  }
};

const langs = Object.keys(translations);

for (const lang of langs) {
  const filePath = path.join(localesDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    
    // ensure 'os' namespace exists
    if (!data.os) {
      data.os = {};
    }
    
    // update strings
    const osTrans = translations[lang];
    for (const key of Object.keys(osTrans)) {
      data.os[key] = osTrans[key];
    }
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated OS strings in ${lang}.json`);
  }
}

// Ensure remaining languages get the mock '[lang]' prefix, or english if they don't have it yet!
// The ones we missed: kn, ml, hi, ja, it, es, ru, ar, de, fr, ta, te, ur, zh. Wait, I did those in the FIRST script!
// Let's do a catch-all to just make sure all 23 files have the `os` block!
const allFiles = fs.readdirSync(localesDir).filter(f => f.endsWith('.json'));
allFiles.forEach(file => {
  const langCode = file.replace('.json', '');
  const filePath = path.join(localesDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  
  if (!data.os) {
    data.os = {};
  }
  
  // if missing any keys, add them as [lang]
  for (const key of Object.keys(enOs)) {
    if (!data.os[key]) {
      data.os[key] = `[${langCode}] ${enOs[key]}`;
    }
  }
  
  // Specifically map ML from prompt:
  if (langCode === 'ml') {
    data.os.aiItinerary = "AI യാത്രാവിവരണം";
    data.os.vibeMarket = "വൈബ് മാർക്കറ്റ്";
  }

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
