const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');
const files = fs.readdirSync(localesDir).filter(f => f.endsWith('.json'));

const newKeys = {
  "menu": {
    "sections": {
      "coreHub": "Core Hub",
      "aiPlanning": "AI & Planning",
      "arImmersive": "AR & Immersive",
      "foodGastronomy": "Food & Gastronomy",
      "wellnessFitness": "Wellness & Fitness",
      "ecoSustainability": "Eco & Sustainability",
      "nightlifeEntertainment": "Nightlife & Entertainment",
      "localCulture": "Local Culture",
      "safetyLegal": "Safety & Legal",
      "transitFinance": "Transit & Finance",
      "socialGames": "Social & Games",
      "creativeMemories": "Creative & Memories",
      "administration": "Administration",
      "partners": "Partners"
    },
    "items": {
      "explore": "Explore",
      "itineraries": "Itineraries",
      "aiItinerary": "AI Itinerary",
      "bookingHub": "Booking Hub",
      "digitalTailor": "Digital Tailor",
      "wallet": "Wallet",
      "esim": "eSIM",
      "store": "Store",
      "journal": "Journal",
      "profile": "Profile",
      "scenarioPlanner": "Scenario Planner",
      "serendipityEngine": "Serendipity Engine",
      "cognitiveLoadBalancer": "Cognitive Load Balancer",
      "aiTravelMentor": "AI Travel Mentor",
      "moodSynthesis": "Mood Synthesis",
      "habitIntegration": "Habit Integration",
      "budgetSynthesis": "Budget Synthesis",
      "weatherAdaptive": "Weather Adaptive",
      "pathfinder": "Pathfinder",
      "flavorSeeker": "Flavor Seeker",
      "abTesting": "AB Testing",
      "dreamWeaver": "Dream Weaver",
      "challengeGenerator": "Challenge Generator",
      "arWayfinding": "AR Wayfinding",
      "landmarkLens": "Landmark Lens",
      "arStorytelling": "AR Storytelling",
      "heritageMirror": "Heritage Mirror",
      "arMenu": "AR Menu",
      "paintTheTown": "Paint The Town",
      "skyGazer": "Sky Gazer",
      "arTimeLapse": "AR Time Lapse",
      "arArtGallery": "AR Art Gallery",
      "arTransitXRay": "AR Transit X-Ray",
      "arGhostTours": "AR Ghost Tours",
      "arHistorical": "AR Historical",
      "arAncientRuins": "AR Ancient Ruins",
      "memoryPalace": "Memory Palace",
      "vrPreTrip": "VR Pre-Trip",
      "vrImmobileTravel": "VR Immobile Travel",
      "vrMeditation": "VR Meditation",
      "vrExtremeSports": "VR Extreme Sports",
      "postcardStudio": "Postcard Studio",
      "videoTeaser": "Video Teaser",
      "audioGuide": "Audio Guide",
      "localFoodBingo": "Local Food Bingo",
      "localProduceChallenge": "Local Produce Challenge",
      "mysteryMeal": "Mystery Meal",
      "chefsTable": "Chef's Table",
      "streetFoodTour": "Street Food Tour",
      "wineTasting": "Wine Tasting",
      "cocktailCompanion": "Cocktail Companion",
      "breweryTour": "Brewery Tour",
      "coffeeConnoisseur": "Coffee Connoisseur",
      "teaCeremony": "Tea Ceremony",
      "veganFinder": "Vegan Finder",
      "glutenFreeGuide": "Gluten Free Guide",
      "foodHistory": "Food History",
      "recipeCollector": "Recipe Collector",
      "forageMap": "Forage Map",
      "homeCookedMeal": "Home Cooked Meal",
      "coffeeWithLocal": "Coffee With Local",
      "farmToTable": "Farm To Table",
      "foodBloggerMode": "Food Blogger Mode",
      "flavorDna": "Flavor DNA",
      "digitalDetox": "Digital Detox",
      "bioDataMonitor": "Bio Data Monitor",
      "personalizedMeditation": "Personalized Meditation",
      "findAGym": "Find A Gym",
      "runningTrails": "Running Trails",
      "travelSleepTracker": "Travel Sleep Tracker",
      "mentalHealthSupport": "Mental Health Support",
      "spaWellness": "Spa & Wellness",
      "travelWorkouts": "Travel Workouts",
      "mindfulWalking": "Mindful Walking",
      "stressMonitor": "Stress Monitor",
      "hydrationReminder": "Hydration Reminder",
      "calorieTracker": "Calorie Tracker",
      "circadianProtocol": "Circadian Protocol",
      "carbonSynthesis": "Carbon Synthesis",
      "ecoWarriorQuests": "Eco Warrior Quests",
      "leavePositiveTrace": "Leave Positive Trace",
      "greenTransitScore": "Green Transit Score",
      "reforestationRewards": "Reforestation Rewards",
      "sustainablePartners": "Sustainable Partners",
      "waterRefillFinder": "Water Refill Finder",
      "wildlifeSighting": "Wildlife Sighting",
      "conservationCircle": "Conservation Circle",
      "animalTranslator": "Animal Translator",
      "transportCo2": "Transport CO2",
      "leaveNoTrace": "Leave No Trace",
      "volunteerOpportunities": "Volunteer Opportunities",
      "ecoLeaderboard": "Eco Leaderboard",
      "localMusicScene": "Local Music Scene",
      "liveMusicFinder": "Live Music Finder",
      "festivalForecaster": "Festival Forecaster",
      "clubbingGuide": "Clubbing Guide",
      "comedyClub": "Comedy Club",
      "theaterBooking": "Theater Booking",
      "karaokeFinder": "Karaoke Finder",
      "speakeasyGuide": "Speakeasy Guide",
      "nightMarket": "Night Market",
      "rooftopBar": "Rooftop Bar",
      "stargazingSpots": "Stargazing Spots",
      "travelSoundtrack": "Travel Soundtrack",
      "cinemaLanguage": "Cinema Language",
      "lostInTranslationGame": "Lost In Translation Game",
      "culturalEtiquette": "Cultural Etiquette",
      "mythFolklore": "Myth & Folklore",
      "ancestryTrail": "Ancestry Trail",
      "localLegends": "Local Legends",
      "localSlangChallenge": "Local Slang Challenge",
      "localDialectTutor": "Local Dialect Tutor",
      "skillExchangeHub": "Skill Exchange Hub",
      "streetArtSagas": "Street Art Sagas",
      "translationEarbuds": "Translation Earbuds",
      "translator": "Translator",
      "localHeroConnect": "Local Hero Connect",
      "liveLikeALocal": "Live Like A Local",
      "secretLocalSpots": "Secret Local Spots",
      "artisanFinder": "Artisan Finder",
      "travelInsurance": "Travel Insurance",
      "digitalPassport": "Digital Passport",
      "scamAlertRadar": "Scam Alert Radar",
      "safetySwarm": "Safety Swarm",
      "virtualEmbassy": "Virtual Embassy",
      "emergencyPhrases": "Emergency Phrases",
      "findADoctor": "Find A Doctor",
      "waterQualityAlerts": "Water Quality Alerts",
      "airQualityAlerts": "Air Quality Alerts",
      "disasterWarnings": "Disaster Warnings",
      "allergenAlert": "Allergen Alert",
      "visaPassport": "Visa & Passport",
      "vaccination": "Vaccination",
      "getMeHome": "Get Me Home",
      "lostLuggage": "Lost Luggage",
      "drivingLaws": "Driving Laws",
      "currencyExchange": "Currency Exchange",
      "flightDelayPredictor": "Flight Delay Predictor",
      "bikeScooterRental": "Bike & Scooter Rental",
      "ferryBooking": "Ferry Booking",
      "scenicRoutePlanner": "Scenic Route Planner",
      "layoverAdventure": "Layover Adventure",
      "publicTransportPass": "Public Transport Pass",
      "atmFinder": "ATM Finder",
      "taxFreeShopping": "Tax Free Shopping",
      "ticketAggregator": "Ticket Aggregator",
      "travelerCarpooling": "Traveler Carpooling",
      "lastMileTransit": "Last Mile Transit",
      "rentalSynthesizer": "Rental Synthesizer",
      "digitalNomadHub": "Digital Nomad Hub",
      "travelersGuilds": "Travelers Guilds",
      "factionWars": "Faction Wars",
      "bountyBoard": "Bounty Board",
      "travelCharades": "Travel Charades",
      "globalTreasureHunt": "Global Treasure Hunt",
      "cityCaptureTheFlag": "City Capture The Flag",
      "travelerDuels": "Traveler Duels",
      "sharedExpense": "Shared Expense",
      "payItForward": "Pay It Forward",
      "collaborativeDiary": "Collaborative Diary",
      "itineraryTrading": "Itinerary Trading",
      "mysteryPenPal": "Mystery Pen Pal",
      "guessTheLocation": "Guess The Location",
      "echoesOfPastTravelers": "Echoes of Past Travelers",
      "aiStoryScout": "AI Story Scout",
      "memeMyTrip": "Meme My Trip",
      "aiBlogger": "AI Blogger",
      "travelPoem": "Travel Poem",
      "memoryMapper": "Memory Mapper",
      "sensoryJournal": "Sensory Journal",
      "historicalDialogueBot": "Historical Dialogue Bot",
      "postcardAi": "Postcard AI",
      "digitalSouvenirForging": "Digital Souvenir Forging",
      "travelTattooDesign": "Travel Tattoo Design",
      "tripColorPalette": "Trip Color Palette",
      "vibeFilters": "Vibe Filters",
      "collaborativeScrapbook": "Collaborative Scrapbook",
      "travelLegacy": "Travel Legacy",
      "photoOfTheDay": "Photo Of The Day",
      "gifMaker": "Gif Maker",
      "vlogGenerator": "Vlog Generator",
      "adminConsole": "Admin Console",
      "partnerDashboard": "Partner Dashboard"
    }
  }
};

files.forEach(file => {
  const filePath = path.join(localesDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.menu = newKeys.menu;
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});

console.log("Updated language files.");
